c_emulator/riscv_sim.c
I made this to try to fix a problem with TestRig where instructions that cause a fetch exception (e.g. CHERI PCC error) do not produce an RVFI report and instead enter a loop executing the same instruction. I'm not sure what 'need_instr' was intended to do but does not seem to be what we want. Maybe you have an idea? It's a bit untested until someone (e.g. @PeterRugg) can give it a go.
=> Attempt to fix RVFI for instruction fetch exceptions. 

Makefile
> Recursive make commands should always use the variable MAKE, not the
explicit command name ‘make’
See:
https://www.gnu.org/software/make/manual/make.html#MAKE-Variable
=> Invoke recursive make using $(MAKE) as GNU recommends

model/riscv_fdext_control.sail, model/riscv_fdext_regs.sail
=> Report correct value in trace for CSR writes to frm and fflags

model/riscv_mem.sail, model/riscv_sys_regs.sail, model/riscv_vmem_rv32.sail, model/riscv_vmem_rv64.sail
=> Fix mstatus.MPRV fetches

model/riscv_insts_dext.sail, model/riscv_insts_fext.sail
Fixes #52, along with some minor cleanup to make the fix a little simpler.
=> Fix FMIN/FMAX when QNaN+SNaN

build_simulators.sh
Test for bad return code from make
=> check error status returns from make

model/riscv_fetch_rvfi.sail
This is something that wasn't yet decided in the DII spec, but has become clear is something we want.
=> Perform PTE checks on DII fetch (with jrtc27)

model/riscv_mem.sail
=> Fix the non-RVFI_DII build

model/riscv_vmem_common.sail
This is a fix for #101.
CC: @cento
=> Fix incorrect SV48_Vaddr bitfield

c_emulator/riscv_platform.c, c_emulator/riscv_platform.h, c_emulator/riscv_platform_impl.c, c_emulator/riscv_platform_impl.h, c_emulator/riscv_sim.c, handwritten_support/0.11/riscv_extras.lem, handwritten_support/0.11/riscv_extras_sequential.lem, handwritten_support/riscv_extras.lem, handwritten_support/riscv_extras_sequential.lem, model/riscv_fdext_regs.sail, model/riscv_insts_cdext.sail, model/riscv_insts_cfext.sail, model/riscv_insts_dext.sail, model/riscv_insts_fext.sail, model/riscv_sys_control.sail, model/riscv_sys_regs.sail, ocaml_emulator/platform.ml
=> Revert "Initial introduction of zfinx"

c_emulator/riscv_sim.c, ocaml_emulator/riscv_ocaml_sim.ml
Fix for the issue #111 
Now by default Sail with dump 32-bit (word) length signatures in the signature file.
To make it configurable `signature-granularity=<num-bytes-per-line>` cli is added, just like we have in spike.
=> Configurable word size for test signature file output

model/riscv_fdext_regs.sail, model/riscv_insts_zfh.sail, model/riscv_sys_regs.sail
Added support for Zhinx extension ([spec](https://github.com/riscv/riscv-zfinx/blob/main/zfinx-1.0.0.pdf))
=> Add support for Zhinx extension

.github/workflows/compile.yml
=> Bump CI to Ubuntu 22.04

.github/workflows/compile.yml
This PR adds the capability to run the tests manually without depending on a new change to trigger it.
=> Add a new recipe to run the Sail tests manually via GH Actions

model/riscv_mem.sail
This matches QEMU and makes more sense IMO.
CC: @PeterRugg @jrtc27
=> RVFI: only report write data if the write succeeds

.github/workflows/compile.yml, .github/workflows/test-results.yml
Update the versions of some of the Github actions, as some of the older action versions used parts of the github API that are deprecated and due to be removed.
=> Some simple CI housekeeping

model/prelude.sail
Some less-than/greater-than operators were missing. This adds the full set.
=> Add missing comparison operators

Makefile, etc/headache_config
Potential fix https://github.com/riscv/sail-riscv/issues/418
Do we need to add anything else @Timmmm ?
Thx,
Abhinav.
=> Remove `etc` directory

README.md
Update ITYPE and SRET examples in the README to match the current implementation in the actual model
=> Update README example code

c_emulator/riscv_sim.c
=> Add enable-svinval option

model/riscv_insts_zca.sail
fix the log error mentioned in #537
=> fix c.j imm log wrong

model/riscv_pmp_control.sail
Issue # [587](https://github.com/riscv/sail-riscv/issues/587#issue-2580600767)
=> PMP NA4 Region Upper address calculation updated

handwritten_support/riscv_extras.lem, handwritten_support/riscv_extras.v, handwritten_support/riscv_extras_sequential.lem, model/riscv_sys_regs.sail
Remove remaining references to the N extension that were leftover from #584.
=> Remove N extension flag

Makefile
I don't believe this backend exists any more.
=> Remove c2 Makefile target

Makefile, coq-sail-riscv.opam, handwritten_support/mem_metadata.v, handwritten_support/riscv_extras.v, model/riscv_termination.sail, model/riscv_termination_rv32.sail, model/riscv_termination_rv64.sail
It requires an up-to-date development version of Sail because I fixed a couple of bugs while working on it, but only for Coq output, it shouldn't affect any other target.
=> Update support for Coq output

model/riscv_insts_base.sail
=> Add missing ifs with SHIFTIOP mapping

model/prelude.sail
Adds a few needed annotations that currently cause errors in the Lean export of the model
=> Add annotations for Lean export

README.md, model/CMakeLists.txt, model/riscv_extensions.sail, model/riscv_platform.sail, model/riscv_smcntrpmf.sail, model/riscv_step.sail
This PR is derived from #265, which has not been advanced for nearly two years, and since Smcntrpmf has already been ratified, it should be continued to add support
=> Support Smcntrpmf in Sail-RISCV

handwritten_support/RiscvExtras.lean, model/CMakeLists.txt, model/prelude.sail
This is still work in progress
=> Handwritten support for the Lean backend

handwritten_support/RiscvExtras.lean
Adapt to the [specialization patch](https://github.com/rems-project/sail/pull/1084).
=> Lean: update handwritten support

c_emulator/riscv_sim.c
At a few hundred thousand instructions per second, 32-bit `int total_insns` will overflow in a few hours. If the limit  is too high, it will be parsed incorrectly without error and execution stops at a somewhat arbitrary point (or not at all).
This PR therefore changes the types to `long`. 
I've also switched to using `strtol` for parsing the `insns_limit` command line argument in order to get error checking (and to make it possible to use hex notation).
=>  store `total_insns` and `insn_limit` as `uint64_t`, not `int`

CODE_STYLE.md
IIRC this was discussed in the golden-model meeting.
=> Update CODE_STYLE to suggest the use of `newtype`.

CODE_STYLE.md
Not sure if this sounds too prescriptive, open to suggestions.
=> Update code-style to add suggestion about formatting mapping clauses and the use of `when`.

model/riscv_sys_regs.sail
Another remnant from the N extension I believe.
=> Remove mentions of ustatus

README.md
This can be improved as we settle on a workflow, but at least the README is not wrong now.
=> Update README with initial help on the new model configuration scheme.

c_emulator/riscv_sim.cpp
=> Remove unused cli opts

model/arithmetic.sail, model/prelude.sail, model/riscv_insts_zbkb.sail, model/riscv_insts_zvbb.sail
Replace `reverse` overload with direct calls to `reverse_bits`
Fixes #825
=> Remove reverse overload

CMakeLists.txt
=> Add URL_HASH to GMP download

model/riscv_fetch.sail, model/riscv_fetch_rvfi.sail, model/riscv_mem.sail, model/riscv_platform.sail, model/riscv_pmp_control.sail, model/riscv_sys_regs.sail, model/riscv_types.sail, model/riscv_vmem.sail, model/riscv_vmem_pte.sail, model/riscv_vmem_ptw.sail, model/riscv_vmem_types.sail
Do you put a period after your commit messages?
for closing https://github.com/riscv/sail-riscv/issues/808
=> Rename the Execute access type to InstructionFetch

model/riscv_vmem.sail
part of #433 
I'm not quite sure about the functionality of `ext_ptw` here
=> Use result type instead of PTW_Result

CMakeLists.txt
See https://www.gnu.org/server/mirror.html
You can see the expected result at https://github.com/Arielfoever/sail-riscv/actions/runs/14609337684/job/40984351177
This will fix https://github.com/riscv/sail-riscv/pull/876#pullrequestreview-2783448510
=> CMakeLists: Add mirrors of gmp.

model/riscv_termination.sail
This fixes the Lean build, at least.
=> Fix termination measure for `currentlyEnabled`

README.md
=> Update README build instructions and general cleanup

c_emulator/riscv_platform.cpp, c_emulator/riscv_sail.h, c_emulator/riscv_sim.cpp, model/riscv_insts_zbb.sail, model/riscv_types.sail
- Convert enum-bits covervsions to mappings where possible
- Remove unused types
=> riscv_types cleanup

README.md
Simple PR to test the merge queue.
=> Update README to reflect the cleanup in 587294254.

c_emulator/riscv_callbacks.cpp, c_emulator/riscv_callbacks.h, c_emulator/riscv_sail.h, model/riscv_callbacks.sail, model/riscv_mem.sail
This should be the last PR related to printing. I added the access type to `mem_write_callback()`.
=> Fix memory write/read print output

model/riscv_pmp_control.sail
=> Fix to_bits_unsafe() in PMP code

model/riscv_termination.sail
@ineol @tobiasgrosser @bacam It would be great for this list to be something Sail can output so that this doesn't keep happening. Any chance that would be possible?
=> Fix lean currentlyEnabled termination issue introduced by #904

model/riscv_insts_zvbb.sail
maybe_vmask() will emit its own comma when needed.
=> fix: maybe_vmask() should not be prefixed with sep()

.github/workflows/compile.yml, .github/workflows/release.yml, .github/workflows/rocq.yml, CMakeLists.txt, Makefile.old, README.md, coq-sail-riscv.opam
I also used the `SAIL_VERSION` env var in all the workflows to make them a bit more consistent.
=> Update Sail compiler to 0.19.1

model/riscv_insts_vext_arith.sail, model/riscv_insts_vext_fp_red.sail, model/riscv_insts_vext_red.sail
This is necessary for future improvements to the vector types.
=> Add/move assertions for SEW_widen size

model/CMakeLists.txt, model/rvfi_dii.sail, model/rvfi_dii_v1.sail, model/rvfi_dii_v2.sail
A small change to make the code cleaner
=> Split rvfi_dii v1 and v2

model/riscv_sys_regs.sail
The logged values were mstatus,mie and mip; fix them to be sstatus, sie and sip instead.
=> Fix the logged value for writes to sstatus, sie and sip.

model/riscv_insts_mext.sail
In this case truncation is intentional. Also some minor style cleanups.
=> Use to_bits_truncate in the M extension

model/riscv_insts_zcf.sail
=> Fix scaling of c.flwsp immediate in assembly

config/default.json, model/riscv_sys_control.sail, model/riscv_sys_regs.sail
This is required if you support Zkr.
=> Add mseccfg CSR

model/CMakeLists.txt
The schema is generated in the default (c_emulator) build target variant.
=> Add the config schema to the build.

model/riscv_insts_fext.sail
Use `size_enc` to deduplicate these.
=> Merge float load/store encdec clauses

model/riscv_insts_base.sail, model/riscv_jalr_seq.sail
Create a function that JAL, JALR and branch instructions can all use for jumping to a target address.
=> Extract jumping to a PC into a function

model/riscv_sys_control.sail
While here, fix some whitespace alignment.
=> Remove unused tuple in match of `exception_handler`.

test/first_party/CMakeLists.txt
Fixes #1255 and gets CI passing again.
=> Fix macOS first-party test linking

c_emulator/riscv_sim.cpp
This was added in one place, but not here.
=> Add missing sail_set_abstract_base_E_enabled()

CODE_STYLE.md, model/riscv_ext_regs.sail, model/riscv_insts_svinval.sail, model/riscv_insts_zicbop.sail, model/riscv_zicbop_types.sail
Also update a few stragglers that were missed due to rebasing etc.
=> Update style guide to prefer block comments
