riscv/sail-riscv

model/riscv_addr_checks.sail
model/riscv_insts_aext.sail
model/riscv_insts_base.sail

This will assist with implementing CHERI capability mode.

Add base address register as extra argument to ext_data_check_addr hook

---

c_emulator/riscv_sim.c

This untested but trivial change fixes a clear bug in the filename displayed when using -T.

Display correct filename in message when using -T

---

README.md

Two suggested edits to the README based on my attempt to build the project.  One is a link explaining how to install sail via opam at the appropriate place, and the other documents a dependency on `dtc` that seems required to use the ocaml simulator.

Two small README updates.

---

c_emulator/riscv_sim.c

These two command-line flags printed the reverse of what they were actually doing.

Correction to flag descriptions

---

Makefile

This is a minor change to the Makefile to clean up a few small things.
I had bigger plans to enable incremental recompilation of the C sources (instead of always having to recompile the 4MB+ `riscv_model_RV64.c` every time I touch `riscv_sim.c`) but I realized that sometimes the C sources are compiled with -DRVFI_DII and sometimes not, so we would need to build two sets of `*.o` files, one with -DRVFI_DII and one without, and I decided that's not worth the hassle.

Makefile upgrade

---

c_emulator/riscv_sim.c

I've made some local changes to the command-line options in `riscv_sim.c`, and every time I merge/rebase upstream changes it's a mess because the options are all in one line. This change splits that long string up into one line per option.
This will make future changes easier to read and merge, since adding and removing options will show up as entire lines that change instead of a few characters in the middle of the line.

Expand getopt_long option string to multiple lines

---

Makefile

Change a381a83 added `-dno_cast` to the Sail command line. But there are two places where `SAIL` is defined in the Makefile (depending on whether we're running from opam or built from repo in `SAIL_DIR`), and that change only affected one of the two.
Shouldn't that flag apply to both?
This change uses `SAIL_FLAGS` to apply `-dno_cast` to the Sail command line no matter where it's run from.
(There is the possibility that the version of Sail in opam is too old to support the `-dno_cast` flag, so a381a83 deliberately did not apply the flag to that version. If so, that should be explained somewhere, at least in the commit message.)
(Additional nit: I'm unable to fully comprehend the commit message in a381a83, partly because it's not written in [imperative …

Run Sail with -dno_cast even when it comes from opam package

---

Makefile
model/riscv_ext_regs.sail
model/riscv_insts_base.sail
model/riscv_insts_next.sail
model/riscv_insts_zicsr.sail
model/riscv_sys_exceptions.sail

This adds an extension point to allow extensions to veto CSR access similar to #23 (in fact I based this on that branch so those changes are also included here).

CSR extension point

---

Makefile
model/riscv_insts_base.sail
model/riscv_insts_next.sail
model/riscv_sys_exceptions.sail

This adds an extension point to allow extensions to block xret instructions. This could be used by CHERI to enforce the 'access system registers' permission.

Xret extension point

---

model/riscv_fetch.sail
model/riscv_mem.sail
model/riscv_platform.sail

The spec does not spell this out clearly, but I assume the intent is that AMOs
always give AMO (aliases store) faults and never the load counterparts. I have
opened https://github.com/riscv/riscv-isa-manual/issues/469 to track this.

Generate correct cause for AMO faults

---

Makefile
c_emulator/riscv_sim.c

idx, passed as longindex to getopt_long, is updated every time a long option is parsed to be the index of that option in the options array, not argv. We should instead use optind as in the non-RVFI-DII case, and we can remove the variable to avoid confusion since it is unused.
I have also included a convenience change so building RVFI behaves like non-RVFI, producing an executable suffixed with the architecture and isolating its intermediate build products.

Fix parsing long options in the C emulator for RVFI-DII

---

c_emulator/riscv_sim.c

This fixes a firewall popup showing up on every start when using macOS.

Only listen for RVFI-DII messages on 127.0.0.1

---

model/riscv_insts_zicsr.sail
model/riscv_pmp_regs.sail

* pmp8cfg and pmp9cfg were not writable due to a typo in the source.
* Bits 5 and 6 of each 8-bit field must be masked to 0. (Is there a better way to do this using bitfield? I couldn't figure that out.)

Fix several pmpcfg issues

---

model/riscv_insts_base.sail

I observed that when a store instruction has invalid PMP permissions and takes an access fault, the `mtval` register was being written with the physical address. It should always be a virtual address.
I renamed some identifiers in the code in the first few commits to make the problem more obvious, then fixed it in the final commit.

Fix mtval when store gets bad PMP

---

c_emulator/riscv_sim.c
model/riscv_ptw.sail
model/riscv_vmem_sv32.sail
model/riscv_vmem_sv39.sail
model/riscv_vmem_sv48.sail

Otherwise there's no use for PTW_Ext_Error. This is required for sail-cheri-riscv to be able to make use of its own page table exceptions. The alternative to this is to pass the ext_ptw to translationException, but given PTW_Ext_Error exists it seems this was the intended way, and aligns with how access faults vs page faults are distinguished.

Allow extensions to override page fault causes

---

model/riscv_insts_aext.sail
model/riscv_iris.sail
model/riscv_pte.sail
model/riscv_ptw.sail
model/riscv_types.sail
model/riscv_vmem_types.sail

This redoes https://github.com/rems-project/sail-riscv/pull/57 without
nearly as much excitement.  We sill want it for CHERI, so that we can
signal from the instruction to the PTW whether we are prepared to load a
capability (or will strip any tags that we load) and whether the store
will (or might) set a tag.

A kinder, gentler splitting of ext_access_type's ReadWrite

---

model/riscv_pte.sail
model/riscv_vmem_sv32.sail

Just because they're not present in the SV32 PTE doesn't mean that
models necessarily need to interpret them as zeros; any constant will do
just fine.  This allows extensions (like CHERI) that have both RV32 and
RV64 versions to define more standard idiomatic interpretation to the
bits within the PTE extension field.

SV32: allow external specification of PTE extension bits

---

model/riscv_csr_map.sail
model/riscv_sys_control.sail
model/riscv_sys_regs.sail

The `mcountinhibit` CSR was missing a mapping for the disassembler, and an entry in `is_CSR_defined()`. CSR read and write instructions to this CSR were taking an illegal instruction exception.
Update: also implemented the IR bit to squash increment of `minstret`.

Add missing pieces to mcountinhibit CSR

---

model/riscv_sys_regs.sail

The `sip` register is special in that is a restricted view of `mip`. Only the bits delegated to S-mode by `mideleg` are visible in `sip`.
Writing to `sip` when `ssip` is not delegated should not change `mip.ssip`.
The Sail model was mistakenly writing 0 to `mip.ssip`, instead of leaving the previous value untouched.

Bug fix: when writing CSR sip, ignore attempt to change undelegated SSIP

---

model/riscv_insts_base.sail

The ISA spec says that EBREAK and ECALL do not count as committed instructions (and therefore shouldn't increment `minstret`), but it doesn't say anything like that about MRET or SRET. Spike increments `minstret` for those two instructions.
For some reason the Sail model had MRET and SRET returning RETIRE_FAIL instead of RETIRE_SUCCESS. If I am reading the code correctly, this return code is only used to affect the increment of `minstret`, and therefore this change should have no other effects.

MRET and SRET should increment minstret

---

model/riscv_sys_regs.sail

A CSRW to the `sstatus` shadow register was erroneously allowed to write to the `uie` and `upie` bits of `mstatus`, even when those bits are supposed to be hardwired to 0 when the N-extension (user-mode interrupts) is not present.
By calling `legalize_mstatus()` I avoid duplicating this logic in `legalize_sstatus()`.

Prevent CSRW to sstatus from modifying uie & upie if N-ext not present

---

model/riscv_insts_aext.sail

The RISC-V spec. only shows LR / SC / AMOs for word and double widths
even though the encoding would naturally extend to other widths (it is
a little unclear). Previously the Sail model would decode the unused
widths but throw an internal error in execute. With this change the
unused widths will not be decoded and will cause illegal instruction
exceptions instead.

Fix internal error caused by invalid LR / SC / AMO widths.

---

model/riscv_pmp_control.sail

The PMP address match logic misses some corner cases.
Since an entry's legal address is [lo, hi), if one tries to access hi, the address matching result of this entry should be PMP_NoMatch rather than PMP_PartialMatch.
Another corner case is that one tries to access lo, assume width > 0, then address + width = lo should be PMP_NoMatch rather than PMP_PartialMatch (that address should locate in the previous entry).

PMP address match misses some corner cases

---

Makefile
c_emulator/riscv_sail.h
c_emulator/riscv_sim.c
model/riscv_fetch_rvfi.sail
model/riscv_mem.sail
model/riscv_regs.sail
model/riscv_step_rvfi.sail
model/riscv_sys_control.sail
model/rvfi_dii.sail

Format should be fairly extensible and providing all the RVFI fields.
See https://github.com/CTSRD-CHERI/QuickCheckVEngine/pull/7 for
the QCVengine changes.
CC: @PeterRugg  @gameboo

Add support for the new RVFI_DII socket format

---

.gitignore

This prevents git from trying to version the build files in c_emulator/SoftFloat-3e.

Ignore build library files

---

model/riscv_mem.sail
model/riscv_sys_regs.sail
model/riscv_vmem_rv32.sail
model/riscv_vmem_rv64.sail
model/riscv_vmem_sv32.sail
model/riscv_vmem_sv39.sail
model/riscv_vmem_sv48.sail

* Presently, the `walk` functions copy the instruction's memory access type when issuing `mem_read`s for PTEs.  That's readily fixed by the attached commit.
* Additionally, @jrtc27 points out that `mem_read` and `mem_write_value` do not allow the PTW to override the influence of `mstatus` and `cur_privilege` on the `Privilege` used to access the PTEs, while the spec says
PMP checks are also applied to page-table accesses for virtual-address translation, for which the effective privilege mode is S
(in 3.7 of the latest prerelease of 1.12 as of the time of this writing).  That is going to be a more invasive change to `model/riscv_mem.sail`.

PTW accesses memory with incorrect permission checks 

---

c_emulator/riscv_sim.c

This allows a user to change the file that the sail coverage library writes its taken branches to, exposing functionality added to the sail compiler back in August (https://github.com/rems-project/sail/commit/14e5c79b1c6943c88ab36ccc46f073674a76e16c). This allows people to run concurrent copies of the model without the sail_coverage files overwriting one another.

Add option to specify SAILCOV output file

---

model/riscv_addr_checks.sail
model/riscv_addr_checks_common.sail
model/riscv_mem.sail

This is required for implementing memory version support for CHERI.

Add an extension point to allow validation of physical memory accesses.

---

model/riscv_insts_dext.sail
model/riscv_insts_fext.sail

Sail would previously crash when a floating point instruction asked for dynamic rounding mode (meaning look at fcsr.frm), and the rounding mode there wasn't valid (one of the two reserved types), as the fcsr.frm value was passed into encdec_rounding_mode, which doesn't have a case for the reserved encodings. This PR fixes this issue by guarding all uses of the rounding mode on it being valid.

Fix crash when fcsr.frm is invalid

---

model/riscv_insts_zkn.sail
model/riscv_types_kext.sail

Hi there
This PR contains updates from @jrtc27's review [here](https://github.com/riscv/sail-riscv/pull/99#pullrequestreview-786873720) which were missing from the original merge of the scalar cryptography extension code.
- [Commit 1](https://github.com/riscv/sail-riscv/commit/a527ad769c9acba9cba70261c3bd73a1d5a0069c) addresses the [inconsistency of `==` whitespace](https://github.com/riscv/sail-riscv/pull/99#discussion_r734560390)
- [Commit 2](https://github.com/riscv/sail-riscv/commit/c4ad3c16a943de9996224a2439b5488ce4fac359) addresses the [inconsistency of ` );`](https://github.com/riscv/sail-riscv/pull/99#discussion_r734563951) whitespace in the `sha*` instructions.
- [Commit 3](https://github.com/riscv/sail-riscv/commit/53611ff431bac23b438f30bbd214cff3c55c6bb6) tries to address …

Scalar crypto - post code review improvments

---

c_emulator/riscv_platform.c
c_emulator/riscv_platform.h
c_emulator/riscv_platform_impl.c
c_emulator/riscv_platform_impl.h
c_emulator/riscv_sim.c
handwritten_support/0.11/riscv_extras.lem
handwritten_support/0.11/riscv_extras_sequential.lem
handwritten_support/riscv_extras.lem
handwritten_support/riscv_extras_sequential.lem
model/riscv_csr_map.sail
model/riscv_fdext_control.sail
model/riscv_fdext_regs.sail
model/riscv_insts_dext.sail
model/riscv_insts_fext.sail
model/riscv_sys_control.sail
model/riscv_sys_regs.sail
ocaml_emulator/platform.ml

NB: Smstateen support is missing in the model so enabling the Zfinx extension provides an architectural covert channel via FCSR if privileged software is not aware of Zfinx's existence.
Full diff between the previous PR and this can be seen at https://gist.github.com/jrtc27/c26d373d866a6fac78ec69bc43f6c31f.
Summary of changes:
* sys_enable_fdext() and sys_enable_zfinx() are now mutually-exclusive, reflecting the architectural conflict, which remove the need for some places to check `sys_enable_fdext() & ~(sys_enable_zfinx())` (this is also now verified in init_sys)
* Added asserts to various F-only and Zfinx-only places for safety
* Sign-extend rather than NaN-box single-precision floats on RV64Zfinx
* Reverted nan_(un)box_do/pass changes back to just nan_(un)box
* Added …

Implement support for Zfinx

---

model/riscv_insts_mext.sail
model/riscv_sys_regs.sail

RISC-V Zmmul extension includes following instructions:
- mul
- mulh
- mulhsu
- mulhu
- mulw (RV64 only)
The opcode encodings and instruction semantics are identical to those in the M-extension.
The ISA string is Zmmul.
8.3 Zmmul Extension, Version 0.1 (riscv unpriv spec)

Add Support for Zmmul

---

Makefile
c_emulator/riscv_softfloat.c
c_emulator/riscv_softfloat.h
handwritten_support/0.11/riscv_extras_fdext.lem
handwritten_support/riscv_extras_fdext.lem
model/riscv_fdext_regs.sail
model/riscv_freg_type.sail
model/riscv_insts_dext.sail
model/riscv_insts_fext.sail
model/riscv_insts_zfh.sail
model/riscv_softfloat_interface.sail
model/riscv_sys_regs.sail
ocaml_emulator/softfloat.ml
prover_snapshots/hol4/RV32/riscvScript.sml
prover_snapshots/hol4/RV32/riscv_extras_fdextScript.sml
prover_snapshots/hol4/RV64/riscvScript.sml
prover_snapshots/hol4/RV64/riscv_extras_fdextScript.sml
prover_snapshots/isabelle/RV32/Riscv.thy
prover_snapshots/isabelle/RV32/Riscv_extras_fdext.thy
prover_snapshots/isabelle/RV64/Riscv.thy
prover_snapshots/isabelle/RV64/Riscv_extras_fdext.thy

“Zfh” Standard Extensions for Half-Precision Floating-Point, Version 0.1
Chapter 15 in the [draft](https://github.com/riscv/riscv-isa-manual/releases/tag/draft-20211118-d42b61f) spec.
FCVT.Q.H and FCVT.H.Q are not implemented. (Quad-Precision is not supported by sail yet)

Add support for Zfh extension

---

Makefile
model/prelude.sail
model/riscv_insts_zbb.sail
model/riscv_insts_zbc.sail
model/riscv_insts_zbkb.sail
model/riscv_insts_zbkx.sail
model/riscv_sys_regs.sail
model/riscv_types.sail

This request is for Scalar Cryptography Zbkb, Zbkc and Zbkx extensions Support (https://github.com/riscv/riscv-crypto/releases/tag/v1.0.0-rc5-scalar) in the sail Model.

Add support for Scalar Cryptography Zbkb, Zbkc and Zbkx Extensions

---

CODE_STYLE.md
CONTRIBUTING.md

Added notes about copyright headers in code, and a reminder that pull-requests ideally come with an explanation how the correctness of the PR was established.

Improved code-style and contribution documentation

---

.github/workflows/compile.yml
.github/workflows/test-results.yml
test/.gitignore
test/run_fp_tests.sh
test/run_tests.sh

Includes various improvements to the test scripts to make them work in an automated setting and produce better JUnit output.
The separate workflow is needed in order to support pull requests from forks of the repository, since the `on: pull_request` job runs with only limited access to the upstream repository for security reasons. This means the workflow that actually parses and uploads the test results is defined in the default branch (currently master), not in the pull request contents, and so won't actually run until this pull request is merged. I've pushed this series of commits to my own fork, set that branch as the default there and submitted a pull request against that that introduces a regression in order to demonstrate how this will look once merged at …

Run ISA tests in CI

---

Makefile
handwritten_support/riscv_extras.v

This small set of changes to the Coq support files allows recent versions of Coq to build them (by replacing omega with lia), adds a missing axiom for a platform built-in, and improves the namespacing a little.
(Note that the Coq output won't build against the library from the last Sail release due to a bug in that library, but will build using the current repository version of Sail.)

Minimal updates for Coq proof assistant output

---

Makefile
c_emulator/riscv_sail.h

The sail C code generator will emit definions for these structs. The
duplicate definition linker error were worked around by adding -fcommon
in https://github.com/riscv/sail-riscv/commit/ffea7a39c32a210a446379aeda0eabcec4918ed6. This commit fixes the
underlying issue by declaring the variables as `extern`.

Fix build without -fcommon

---

model/riscv_step.sail

This option causes handle_illegal to pass instbits as the value to set
for xtval, but instbits is never set so it ends up being 0 just as if
the option was never enabled. Fix this by initialising instbits during
fetch; we could make this conditional on whether the option is enabled
but that seems unnecessary and introduces tighter coupling.
Note that this option appears to have always been broken; when it was
originally added, instbits was only written two in two cases which were
both dead code and later removed in eb176111887b.
Closes: #173

riscv_step: Fix -i/--mtval-has-illegal-inst-bits option

---

model/riscv_insts_zbkx.sail

This seems to be a copy&paste issue from xperm8. 
This fix brings `sail_riscv` in line with spike for the xperm4 instruction semantics.
Signed-off-by: Jan Henrik Weinstock <jan@mwa.re>

Fix xperm4 index calculation

---

model/riscv_insts_zbkb.sail

Currently, the result of packw is zero-extended, but according to spec, packw should sign-extend its result to 64bit.
This sign-extension is also in accordance with the other simulators:
Spike: https://github.com/riscv-software-src/riscv-isa-sim/blob/86d9fe49eda1fff863a43e682015216a25cc72f3/riscv/insns/packw.h#L10
QEMU: https://gitlab.com/qemu-project/qemu/-/blob/master/target/riscv/insn_trans/trans_rvb.c.inc#L540
Signed-off-by: Jan Henrik Weinstock <jan@mwa.re>

Fix packw sign-extension

---

model/riscv_decode_ext.sail
model/riscv_insts_end.sail
model/riscv_step.sail

Previously the decoding hook (`ext_post_decode_hook`) allowed models to override the decoded `ast`. However, this is not sufficient if model extension changes interpretation of fields. Additionally, the assembly printing would always print assembly for the "baseline decode" which resulted in incorrect trace output in the sail-cheri-riscv model.
With the new hook models can implement ext_decode()/ext_decode_compressed() to return an `ast` and for encodings that are not adjusted fall back to the default `encdec`/`encdec_compressed`.

Increase flexibility of the decode hook (and simplify it)

---

c_emulator/riscv_platform.c
c_emulator/riscv_platform_impl.c
c_emulator/riscv_platform_impl.h
c_emulator/riscv_sim.c
model/riscv_platform.sail
model/riscv_sys_regs.sail

This pull request is intended to satisfy issue #209.
The -X switch (plus its long version) causes the Sail function, plat_enable_experimental_extensions(), to return true.
Functionality that is in the experimental stage (such as extensions that have been implemented but have not been
formally ratified) can be conditionally checked with this function.
Two other switches were also added.
The --enable-Smepmp switch can be used to enable the Smepmp functionality.  The Sail function,  plat_enable_smepmp(),
returns the value of the switch (true if the switch exists;  false otherwise).
The --enable-Zicond can be used to enable the Zicond extension.  The Sail function, plat_enable_zicond(), returns
the value of the switch (true if the switch exists; false otherwise).
Note:  the implementations of …

added 3 new command line switches (plus functionality):  -X/--enable-experimental-extensions, --enable-smepmp, --enable-zicond

---

c_emulator/riscv_platform.c
c_emulator/riscv_platform_impl.c
c_emulator/riscv_platform_impl.h
c_emulator/riscv_sim.c
model/riscv_platform.sail
model/riscv_sys_regs.sail

Reverts riscv/sail-riscv#219. Merged without code review and with many issues.

Revert "added 3 new command line switches (plus functionality):  -X/--enable-experimental-extensions, --enable-smepmp, --enable-zicond"

---

Makefile
model/prelude.sail
model/riscv_insts_vext_arith.sail
model/riscv_insts_vext_mem.sail
model/riscv_insts_vext_utils.sail
model/riscv_insts_vext_vset.sail
model/riscv_insts_zicsr.sail
model/riscv_sys_regs.sail
model/riscv_vext_regs.sail
model/riscv_vlen.sail

This PR contains all vector load / store instructions in the file `riscv_insts_vext_mem.sail`, and a small part of other vector instructions in the file `riscv_insts_vext_arith.sail` for the help of running the vector ISA tests. The model generated by this code can pass the vector load / store ISA tests generated by the [rvv-atg](https://github.com/hushenwei2000/rvv-atg) for different configurations. (I specified ELEN and VLEN manually in `riscv_sys_control.sail` when testing my code.) Please send me comments if there are issues in the new code. I'll do my best to get it right soon.

Vector load / store instructions

---

model/riscv_insts_begin.sail
model/riscv_insts_end.sail

This is useful for the sail-cheri-riscv model, where we would like to reuse C_ILLEGAL, but can't right now since it is current defined too late.
It is needed for https://github.com/CTSRD-CHERI/sail-cheri-riscv/pull/69

Move ILLEGAL/C_ILLEGAL ast declaration to riscv_insts_begin.sail

---

model/prelude.sail
model/riscv_analysis.sail
model/riscv_fetch.sail
model/riscv_fetch_rvfi.sail
model/riscv_insts_aext.sail
model/riscv_insts_base.sail
model/riscv_insts_next.sail
model/riscv_insts_zbb.sail
model/riscv_insts_zicsr.sail
model/riscv_jalr_seq.sail
model/riscv_mem.sail
model/riscv_step.sail
model/riscv_sys_control.sail
model/riscv_sys_regs.sail
model/riscv_vmem_sv32.sail
model/riscv_vmem_sv39.sail
model/riscv_vmem_sv48.sail
model/riscv_vmem_tlb.sail

This may be more readable and also matches the sail-cheri-riscv model. For now this keeps ~ overloaded to accept bool, but in the future we may want to consider removing it (which is what I did to find all uses modified in this patch).

Use not() instead of ~() for boolean negation

---

Makefile
model/riscv_insts_vext_arith.sail
model/riscv_insts_vext_mask.sail
model/riscv_insts_vext_mem.sail
model/riscv_insts_vext_utils.sail
model/riscv_insts_vext_vm.sail
model/riscv_sys_regs.sail
model/riscv_vlen.sail

This PR mainly contains vector integer/fixed-point arithmetic instructions (Spec Chapter 11, 12) in `riscv_insts_vext_arith.sail` and vector mask instructions (Spec Chapter 15) in `riscv_insts_vext_mask.sail`. Besides, some arithmetic instructions involving mask registers (Spec 11.4, 11.8, 13.13) are collected in `riscv_insts_vext_vm.sail`, and this PR contains part of them for the help of running mask instruction ISA tests.
The model generated by this code can pass the vector ISA tests generated by the [rvv-atg](https://github.com/hushenwei2000/rvv-atg) for different configurations. (ELEN and VLEN are manually specified in `riscv_sys_control.sail` when compiling the model.) Please send me comments if there are issues in the new code. I'll do my best to get it right soon.

Vector integer/fixed-point arithmetic & mask instructions

---

c_emulator/riscv_sim.c

The -g switch requires an argument.  When an argument is provided,  a seg fault ensues.
Note: This does not happen with the long form of the switch (--signature-granularity).
This fix is quite simple;  a single character addition.  See the single line change.

Fixed an issue with the -g switch: seg fault occurred with required argument

---

model/riscv_sys_regs.sail

It seems inconsistent to me that half-precision loads/stores are allowed if mstatus.FS is set to 0 but single/double-precision ones are illegal.

Check for mstatus.FS when performing half-precision loads/stores

---

Makefile
model/riscv_insts_zicond.sail
model/riscv_sys_regs.sail
model/riscv_types.sail

This implements the Zicond (conditional integer operations) extension, as of version 1.0-draft-20230120.
The Zicond extension acts as a building block for branchless sequences including conditional-arithmetic, conditional-logic and conditional-select/move.
The following instructions constitute Zicond:
- czero.eqz rd, rs1, rs2  =>  rd = (rs2 == 0) ? 0 : rs1
- czero.nez rd, rs1, rs2  =>  rd = (rs2 != 0) ? 0 : rs1
See
https://github.com/riscv/riscv-zicond/releases/download/v1.0-draft-20230120/riscv-zicond_1.0-draft-20230120.pdf
for the proposed specification and usage details.

Add support for the Zicond extension

---

model/riscv_insts_zicsr.sail
model/riscv_step.sail
model/riscv_sys_control.sail
model/riscv_sys_regs.sail

This fixes a small bug in `mcounthinhibit`. In the current code if you set `mcountinhibit=1` then it inhibits the count of that CSR write, whereas the spec says that it should only apply to future instructions:
> Any CSR write takes effect after the writing instruction has otherwise completed.
- From the priviledged spec, section 3.1.10 Hardware Performance Monitor.
Fixes #256

Fix minstret off-by-one when mcountinhibit is set

---

model/riscv_step.sail
model/riscv_sys_regs.sail

PR #257 was aggressively merged before all coding-style issues had been commented on.  This addresses the issues that came up (except the drive-by whitespace cleanup that was contained in PR #257 and would require a force-push) in review.

coding style: fix style issues from merge of PR #257

---

Makefile
model/riscv_insts_vext_mask.sail
model/riscv_insts_vext_red.sail
model/riscv_insts_vext_vm.sail

This PR contains vector reduction instructions (Spec Chapter 14) in `riscv_insts_vext_red.sail` and mask instructions from Chap 11 (integer arithmetic) and 13 (floating-point) in `riscv_insts_vext_vm.sail`. The model generated by this code is tested by the vector ISA tests generated by [rvv-atg](https://github.com/hushenwei2000/rvv-atg) for different configurations. (ELEN and VLEN are manually specified in riscv_sys_control.sail when compiling the model.) Please send me comments if there are issues in the new code.

Vector reduction and mask instructions

---

.clang-format
c_emulator/SoftFloat-3e/.clang-format
c_emulator/riscv_platform.c
c_emulator/riscv_platform.h
c_emulator/riscv_platform_impl.c
c_emulator/riscv_platform_impl.h
c_emulator/riscv_prelude.c
c_emulator/riscv_sail.h
c_emulator/riscv_sim.c
c_emulator/riscv_softfloat.c
c_emulator/riscv_softfloat.h

From my testing it turns out the built-in WebKit style is the closest to the current style. I added a few config options to further reduce the diff and I think the current output looks reasonable. In the future it would be good to add a CI and pre-commit check to enforce that all C code is consistently formatted to reduce the need for reviewers to look for formatting issues.

Add a clang-format configuration and reformat C code

---

.pre-commit-config.yaml

The template that I used when adding it uses hooks from 2020. Update this to the latest version and add a minimum pre-commit version check to ensure we get sensible error messages rather than obscure failures. The minimum chosen here is 2.10 as that is the version shipping with Debian 11 and most other distributions have newer versions. If needed a newer version can always be installed using pip.

Update pre-commit-hooks version

---

.pre-commit-config.yaml

This formats the code with clang-format 15 since the pre-commit hook for clang-format 16 would require a newer version of pre-commit.

Add clang-format to the pre-commit hooks

---

Makefile

We have an Asciidoctor plugin that allows incorporating Sail code into ISA manuals written using asciidoc. See https://github.com/Alasdair/asciidoctor-sail. This requires generating a json file using Sail that indexes the source code in the repository. This commit simply adds a target for creating that to the Makefile.
Currently requires the development version of Sail, but I am working on making a new opam release of Sail for the documentation support, and there should be no harm in getting the Makefile target here set up in advance, or for those who are already using a development build.

Add Sail asciidoc documentation target to Makefile

---

Makefile

We don't need the generated backup files, but it appears to be the only
way to be compatible with both GNU and BSD sed.

Adjust sed arguments for compatibility with BSD sed

---

c_emulator/riscv_platform_impl.h
c_emulator/riscv_prelude.c
c_emulator/riscv_sim.c

This is useful when booting an operating system with tracing enabled
as it allows showing the printed messages on the terminal and storing
the trace log to a separate file.
Example usage:
`./c_emulator/riscv_sim_RV64 -b os-boot/rv64-64mb.dtb -t /dev/stderr os-boot/linux-rv64-64mb.bbl --trace-output /tmp/linux.log`
This PR also includes a second commit to fix --help for options without a corresponding short option (rebase and merge preferred over squash and merge).

Allow redirecting trace output to a file

---

model/riscv_sys_regs.sail

- Updated `legalize_misa` function in the `riscv_sys_regs.sail` in the `model/` directory to add condition If "C" cannot be disabled because of next PC is misaligned, all changes to misa will be suppressed
- Fix for issue #123

If "C" cannot be disabled, all changes to misa must be suppressed

---

.gitignore
model/prelude.sail
model/riscv_sys_control.sail
model/riscv_vmem_sv32.sail
model/riscv_vmem_sv39.sail
model/riscv_vmem_sv48.sail

Various minor Sail compilation warning fixes.
* Fix warning about duplicated xor_vec
* Fix warning about redundant `_` case in match.
* Fix warning about redundant type annotations on w_pte
Also some minor improvements
* Add `z3_problems` to `.gitignore`.
* Add explicit `var` to `w_pte`. That is good practice and will (hopefully) be required in a future Sail release.
* Fix some accidental hard tabs.

Fix various Sail compilation warnings

---

model/prelude.sail

I intend to make this an error following https://github.com/rems-project/sail/issues/315

Remove non-existent function from overload

---

model/riscv_insts_aext.sail
model/riscv_insts_fext.sail

In some cases we were reporting the translated value instead, but the privileged spec text requires the virtual address:
```
If mtval is written with a nonzero value when a breakpoint,
address-misaligned, access-fault, or page-fault exception occurs on an
instruction fetch, load, or store, then mtval will contain the faulting
virtual address.
```

Report the faulting virtual address in tval

---

c_emulator/riscv_sim.c

This makes it easier to use a separate M-mode bootloader and kernel payload (e.g. OpenSBI fw_jump). It also makes it easier to test booting systems such as FreeBSD without bundling the kernel with the bootloader.

Allow loading more than one ELF binary

---

model/riscv_sys_regs.sail

- Updated `legalize_misa` function in the `riscv_sys_regs.sail` in the `model/` directory to add condition by setting F=0 and D=1 should clear both F and D.
- Fix for issue #300

Setting F=0 and D=1 should result in both F and D being cleared

---

model/riscv_insts_zfa.sail

Likely a cut-and-paste error, the definition for fmaxm.d uses the fmaxm.s mnemonic, which is already used earlier in the same file.
Sadly, `make` fails with the current "master" branch:
```
lem -isa -outdir generated_definitions/isabelle/RV64 -lib Sail=/home/pc/.opam/default/share/sail/src/lem_interp -lib Sail=/home/pc/.opam/default/share/sail/src/gen_lib \
handwritten_support/0.11/riscv_extras.lem handwritten_support/0.11/mem_metadata.lem handwritten_support/0.11/riscv_extras_fdext.lem \
generated_definitions/lem/RV64/riscv_types.lem \
generated_definitions/lem/RV64/riscv.lem
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
File "generated_definitions/lem/RV64/riscv.lem", line 50091, character 9 to line 50091, …
```

Fix fmaxm.d definition

---

model/riscv_sys_control.sail

This should fix the build error that has been reported, although I think in general typing 'make' just does too much by default.

Fix lem build error

---

c_emulator/riscv_softfloat.c
model/riscv_fdext_regs.sail
model/riscv_insts_dext.sail
model/riscv_insts_fext.sail
model/riscv_insts_vext_fp.sail
model/riscv_insts_vext_utils.sail
model/riscv_insts_zfa.sail
model/riscv_insts_zfh.sail
model/riscv_softfloat_interface.sail

Instead of keeping a mirror register in sync with fflags, just return the new flags. This removes the need for `write_fflags()` and `update_softfloat_fflags()`.

Simplify softfloat interface by removing write_fflags

---

model/riscv_analysis.sail
model/riscv_insts_base.sail

SHIFTW and SHIFTIWOP were duplicated. This did not cause any harm except that the disassembly for the SHIFTW version was incorrect. Therefore I removed that version.
The `execute()` functions were identical but the SHIFTW version is slightly neater (only one `[31..0]`) so I applied that to the SHIFTIWOP version.
This should cause no functional changes to the model except that the disassembly will have the extra `w` which is correct.

Remove duplicate shift definitions

---

model/riscv_insts_zfa.sail

In `model/riscv_insts_zfa.sail`, there are quite a few cases where spaces (`spc()`) are utilized instead of separators (`sep()`) between operands:
```
mapping clause assembly = RISCV_FMAXM_D(rs2, rs1, rd)
<-> "fmaxm.d" ^ spc() ^ freg_name(rd)
^ spc() ^ freg_name(rs1)
^ spc() ^ freg_name(rs2)
```
In the assembly representation, spaces are between the mnemonic and its operands, and separators are between operands.
Fix the errant cases.

Use separators, not spaces, between operands

---

c_emulator/riscv_sim.c

Currently when fopen fails, the code attempts to print trace_log, which has type `FILE *`. I think it intends to print the path instead. Fixes the clang warning:
```
c_emulator/riscv_sim.c:1050:48: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘FILE *’ [-Wformat=]
1050 |     fprintf(stderr, "Cannot create trace log '%s': %s\n", trace_log,
|                                               ~^          ~~~~~~~~~
|                                                |          |
|                                                char *     FILE *
```

Fix issue with trace_log in printf

---

model/riscv_insts_aext.sail
model/riscv_insts_base.sail

The operand order for Store-Conditional assembly has the second and third operands reversed.
The RISC-V Instruction Set Manual states:
> ```
> SC.W conditionally writes a word in rs2 to the address in rs1 [...]
> If the SC.W succeeds, the instruction writes the word in rs2 to memory,
> and it writes zero to rd. If the SC.W fails, the instruction does not
> write to memory, and it writes a nonzero value to rd.
> ```
`rd` is for the return code, `rs2` is the value, and `rs1` is the memory address.
For the syntax `sc.w A,B,(C)`:
- `A` is where the result is stored, per convention. So, this is `rd`.
- `B` is the value to be stored. So, this is `rs2`.
- `C` is the address at which to store the value. So, this is `rs1`.
The resulting syntax would be `stc.w rd,rs2,(rs1)`.
The current assembly …

Fix Store-Conditional assembly operand order and add parens

---

model/riscv_insts_cext.sail
model/riscv_insts_cfext.sail
model/riscv_insts_zkn.sail

There are a few places where operand/field names are not consistent across scattered definitions for an instruction.
Here, parameter `rs2` is used for encode/decode and execute, but `rd` is used for the same purpose in the assembly clause:
```
mapping clause encdec_compressed = C_SWSP(ui76 @ ui52, rs2)
<-> 0b110 @ ui52 : bits(4) @ ui76 : bits(2) @ rs2 : regidx @ 0b10
function clause execute (C_SWSP(uimm, rs2)) = {
let imm : bits(12) = zero_extend(uimm @ 0b00);
execute(STORE(imm, rs2, sp, WORD, false, false))
}
mapping clause assembly = C_SWSP(uimm, rd)
<-> "c.swsp" ^ spc() ^ reg_name(rd) ^ sep() ^ hex_bits_6(uimm)
```
Fix these by using the operand names found in
"The RISC-V Instruction Set Manual, Volume I: Unprivileged ISA", document version 20191213, and "RISC-V Cryptography Extensions …

Make consistent operand names

---

model/riscv_insts_vext_mem.sail
model/riscv_insts_vext_red.sail
model/riscv_insts_vext_utils.sail
model/riscv_sys_regs.sail
model/riscv_vext_regs.sail
model/riscv_vlen.sail

We removed these a while ago from everything else, but I guess it didn't happen for vector because it was on a branch.
Removes the warning these produce.

Remove effect annotations from vector extension

---

model/prelude.sail
model/riscv_fdext_regs.sail
model/riscv_regs.sail
model/riscv_step.sail
model/riscv_types.sail
model/riscv_vext_regs.sail
model/riscv_vmem_sv32.sail
model/riscv_vmem_sv39.sail
model/riscv_vmem_sv48.sail

And string_of_bits to bits_str. These are the names that Sail uses so it makes sense to use them.

Rename string_of_int to dec_str

---

model/riscv_csr_map.sail

These were missed when those CSRs were implemented.

Add m/senvcfg to CSR name map

---

.github/workflows/compile.yml

See https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

CI: Update upload-artifact action to v4

---

model/riscv_insts_cext.sail

The restriction was present for `C.SLLI` but was missing for `C.SRLI` and `C.SRAI`.
The format is copied from `C.SLLI`.
Fixes #356

Add RV32 restriction for compressed shift instructions

---

model/prelude.sail
model/prelude_mem.sail
model/prelude_mem_metadata.sail
model/riscv_addr_checks_common.sail
model/riscv_mem.sail
model/riscv_platform.sail
model/riscv_pmp_control.sail
model/riscv_types.sail
model/rvfi_dii.sail

This is the newer, less confusing (and documented!) syntax. Fixes #425.

Replace atom with int

---

c_emulator/riscv_sim.c

Use `PRIu64` for printing `uint64_t`s to prevent compiler warnings.
Follow-up to #414.

Fix error in format specifiers

---

model/riscv_sys_regs.sail

Fix MEnvCall value

---

model/riscv_fdext_regs.sail
model/riscv_insts_zfa.sail
model/riscv_sys_regs.sail

This has been broken for at least 2 years. This fixes the compilation.
Fixes #351

Fix flen=32 compilation

---

model/riscv_mem.sail

* Move `write_knd_of_flags` into its own function.
* Wrap really long lines
* Move PMP check into `access_check` function. This is needed for two reasons:
- The CBO extension needs to do explicit access checks.
- In future it will also check PMAs so the name needs changing.

Clean up memory checking functions slightly

---

model/riscv_insts_aext.sail
model/riscv_insts_base.sail
model/riscv_insts_vext_mem.sail
model/riscv_types.sail

* Remove the duplicate mapping functions.
* Rename to `size_bytes` for consistency with the other two functions.
* Rename `size_bits` to `size_enc`, otherwise it's quite confusing that `size_bits` is not just `8 * size_bytes`.
Fixes #423

Remove & rename duplicate word_width <-> bytes mappings

---

model/riscv_insts_vext_fp.sail
model/riscv_insts_vext_mem.sail
model/riscv_insts_vext_red.sail
model/riscv_insts_vext_utils.sail
model/riscv_sys_regs.sail
model/riscv_vlen.sail

1. Handle unexpected match values as internal errors - they are checked dynamically. 
2. Remove deprecated set syntax

Fix compiler warnings in V extension code

---

model/riscv_csr_map.sail
model/riscv_insts_zicsr.sail
model/riscv_sys_control.sail
model/riscv_sys_regs.sail

This PR is a rebased version of: https://github.com/riscv/sail-riscv/pull/293
Original description:
CSR MCONFIGPTR is defined in RISCV priv spec 1.12 but is missing from the RISC-V SAIL model. This commit adds the read-only CSR MCONFIGPTR.

Add read-only CSR MCONFIGPTR

---

model/riscv_insts_dext.sail

These two instructions are RV64-only, as noted in the comment, but were missing the check. There are other instructions in this file that did have the check so it was just an omission.

Add missing check for RV64 on float conversion instructions

---

README.md

The pre-commit check is strict about this, and even checks non code files such as the README.
This is a one character change that only affects the README, so if this PR makes the CI go green again I will just merge.

Remove trailing whitespace in README

---

model/riscv_insts_zfa.sail

Fixes #388 and fixes #268. fcvtmod.w.d is producing an inexact instead of invalid flag for numbers with an exponent of 31 that are not representable as a two's complement integer (> 2^31 - 1 or < -2^31).
Per #388, 
> According to the Zfa specification, "Floating-point exception flags are raised the same as they would be for FCVT.W.D with the same input operand." According to the unprivileged specification Table 11.4, the invalid exception should be set for inputs > 2^31 - 1 or < -2^31.
This is resolved by adding an additional check when determining the invalid flag for if the integer is > 2^31 - 1 or < -2^31. A similar approach is currently used by Spike.

Correct fcvtmod.w.d flag generation logic for exp == 31

---

model/riscv_insts_zkn.sail
model/riscv_insts_zks.sail

These guards were missing from one side of each clause.

Add missing decoder guards for crypto extensions

---

Makefile

In general we aren't requiring contributors to implement the correct Lem/Isabelle/HOL4/Coq stubs for new extensions (this would almost certainly be way too high a bar for new contributors anyway) so having these in the default set of build targets just means that typing 'make' is broken until those of us who are invested in maintaining those targets can add updates for those stubs.

Remove theorem prover targets from default Makefile rule

---

Makefile

Follow up to https://github.com/riscv/sail-riscv/pull/364 to make sure OPAMCLI is defined when it is used within the shell commands. Also implement Brian's suggestion that variables defined with opam should use `:=` to avoid calling opam each time the variable is expanded.

Makefile: Make sure OPAMCLI is 2.0 in all subshells

---

handwritten_support/riscv_extras.lem

These stub functions are required for building the Riscv.thy file from the generated lem file.
This is required as part of fixing https://github.com/riscv/sail-riscv/issues/399

Add PMP related stubs for Lem to Isabelle build

---

model/riscv_insts_mext.sail
model/riscv_insts_zcb.sail
model/riscv_types.sail

It was brought to my attention that this instruction had a bit of a case of the 'boolean blindness' code smell, where the mul operation was represented as a triple of booleans. This commit refactors the implemention to use a struct with named fields for high, signed1, and signed2.
The C_MUL instruction in Zcb also needs to be changed appropriately
The mul_op struct was added in riscv_types
While I was there I did some light housekeeping w.r.t a comment about a workaround for Sail < 0.15.1, as this is no longer needed. I could split this into a separate commit, but not sure if it's worthwhile to do so.

Refactor MUL instruction

---

model/riscv_pmp_control.sail

The existing PMP code could not handle physical addresses above 32 bits on RV32, which are possible since Sv32 has 34-bit physical addresses, and the PMP registers are in units of 4 bytes, so they can encode 34-bit addresses.
This fixes that by delaying the *4 until the comparison where it can be done using `nat` instead of `xlenbits` which it would overflow.

Handle 34-bit PMP address overflow

---

model/riscv_insts_zbb.sail
model/riscv_insts_zbc.sail
model/riscv_insts_zbkb.sail
model/riscv_insts_zbkx.sail

Implicit `var` declarations will eventually be an error. This makes some implicit `var` declarations explicit.

Add some missing explicit var declarations

---

model/riscv_ext_regs.sail
model/riscv_insts_zicsr.sail

Very minor. Uses an existing type alias.

Replace some bits(12)s with csreg

---

model/riscv_insts_vext_vset.sail

This removes the effect annotation introduced in PR #359 to eliminate the warning when building the model, as effects are no longer used.

Remove effect annotation in vext_vset

---

model/riscv_insts_aext.sail

This matches the style of all the other instructions, which use the decoder mapping for this purpose.

Move haveAtomics() guard for atomic instructions to guard clauses

---

model/riscv_vmem.sail

For Sv32 Page Table Entries are only 4 bytes, but the old code was unconditionally reading and writing 8 bytes.
Fixes #459

Don't read or write 8 bytes for 4-byte PTEs

---

model/riscv_insts_mext.sail

#480 removed if/else clauses but did not reduce whitespace accordingly. This corrects the formatting for riscv_insts_mext

Fix riscv_insts_mext whitespace introduced in #480

---

model/riscv_fdext_regs.sail
model/riscv_regs.sail

There seem to be duplicate functions right now for reg and freg names, (f)reg_name_abi and (f)reg_name. These mappings are the same and only (f)reg_name is used, so remove the unused ones.

Remove unused (f)reg_name_abi functions

---

model/riscv_pmp_regs.sail
model/riscv_vmem.sail
model/riscv_vmem_pte.sail

Update remaining uses of old bitfield syntax and replace with the newer syntax (see #373).
The latest version of the sail repo gives the below deprecation warning, which I assume will be included in the next release of sail. This prevents warning messages when that happens.
```
Warning: Deprecated model/riscv_pmp_regs.sail:71.19-34:
71 |  let match_type = pmpcfg_n[n].A();
|                   ^-------------^
| 
Old bitfield syntax, use '<bitfield>[A]' instead
```

Update bitfield syntax

---

c_emulator/riscv_platform.c
c_emulator/riscv_platform.h

The plat_get_16_random_bits was missing its unit argument, which produces the following warning when using clang:
```
generated_definitions/c/riscv_model_RV64.c:28041:34: warning: passing arguments to 'plat_get_16_random_bits' without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
zseed = plat_get_16_random_bits(UNIT);
```
This commit adds the appropriate argument to the function in the C simulator.

csim: Fix C23 compatability warning

---

model/riscv_fetch.sail
model/riscv_step.sail

* Remove unnecessary `f` variable
* Remove redundant type delcaration for `fetch`.
* Indentation

Minor style fixes

---

model/riscv_mem.sail

These used to be different because they had different effects annotations, but those have since been removed and now they are the same.

Remove duplicate type declarations for mem_read

---

model/hex_bits_signed.sail
model/prelude.sail
model/riscv_insts_base.sail
model/riscv_insts_cext.sail
model/riscv_insts_fext.sail

Fix Issue #21 by adding function to deal with the sign number

fix disassembly problems

---

Makefile

This PR is for fixing the issue #487 so that all available threads work at the same time and the build is finished a lot faster.

Use multiple threads for LTO

---

model/prelude_mem.sail
model/riscv_addr_checks.sail
model/riscv_insts_aext.sail
model/riscv_insts_base.sail
model/riscv_insts_fext.sail
model/riscv_insts_vext_mem.sail

Instead of `word_width` which can only be up to 8 bytes, just use bytes. This allows larger accesses (the limit is increased to 4096), e.g. for `cbo.zero`.
This is a pre-requisite for #455 but should be uncontroversial so I think we can merge it first.
It will require a corresponding (easy) change to the CHERI repo.

Change ext_data_get_addr to use bytes for width

---

model/riscv_insts_aext.sail
model/riscv_insts_base.sail

Simplify the load/store code by removing the unnecessary matches on the access size. I have not done it for float loads/stores because that requires a separate change to make the float code generic over size.
Note, the first commit is #468 - only review the second.

Remove unnecessary matches for loads/stores

---

model/riscv_insts_aext.sail

This is optional according to the spec - you can check afterwards. However
1. it seems extremely unlikely that any real designs will do that for atomics, which (ignoring Zam which the model doesn't support yet), always have to be aligned, and
2. the LR and SC instructions already check before address translation, so this wasn't even consistent.
Ideally in future this would be configurable.
This also includes a minor refactor to reuse the existing alignment checking code.

Check misalignment of AMOs before address translation

---

model/riscv_insts_aext.sail
model/riscv_sys_regs.sail

Specification: https://github.com/ved-rivos/riscv-zaamo-zalrsc

Add Zaamo and Zalrsc

---

model/riscv_sys_control.sail
model/riscv_sys_regs.sail

`mstatus.MPP` legal values are User (`00) (if U-mode implemented), Supervisor (`01) (if S-mode implemented) and Machine (`11). Encoding `10 is illegal.

Add missing mstatus.MPP legalization

---

Makefile

These OCaml files can be read only, in which case copying them for a second build fails. To work around this use the `-f` flag which ignores the read-only-ness.
Fixes #407

Fix consecutive builds of the OCaml emulator

---

README.md

#464 updated which targets are produced by just running make. This brings the README file up to date with those changes.

Update README.md based on updated makefile

---

model/riscv_fdext_regs.sail
model/riscv_regs.sail
model/riscv_types.sail
model/riscv_vext_regs.sail

Replace `forall 'n, 0 < 'n <= *` with `range(0, *)` for register access. With this change, many of them can also switch to using the already defined type aliases.
Fixes #426

Update register reads/writes to use range and type aliases instead of forall 'n

---

c_emulator/riscv_platform.c
c_emulator/riscv_platform.h
c_emulator/riscv_platform_impl.c
c_emulator/riscv_platform_impl.h
c_emulator/riscv_sim.c
model/riscv_sys_control.sail
model/riscv_sys_regs.sail
ocaml_emulator/platform.ml
ocaml_emulator/riscv_ocaml_sim.ml

Specification: https://github.com/riscv/riscv-b

Add B extension

---

model/riscv_insts_aext.sail
model/riscv_sys_regs.sail

Specification: https://github.com/riscv/riscv-zabha
Tested with RISC-V arch. tests and checked against spike.

Add Zabha extension

---

model/prelude.sail
model/riscv_types.sail

Use these mappings and change the other functions to be aliases of them.

Use bool <-> bit mappings from riscv_types.sail

---

model/riscv_csr_ext.sail
model/riscv_csr_map.sail
model/riscv_fdext_control.sail
model/riscv_next_control.sail
model/riscv_sys_control.sail
model/riscv_vext_control.sail

These mode levels are already checked by `csrPriv()` so there's no need to do it again. Removing these checks from `is_CSR_defined()` also means that function name is now correct.
Fixes #402

Remove redundant CSR privilege checks

---

model/riscv_vmem.sail
model/riscv_vmem_tlb.sail

This has a very significant effect on the emulator performance with virtual memory enabled (e.g. when booting Linux).
Having a more realistic TLB can also help expose bugs, like the recent bug in #496. For example with a larger TLB you can add an assertion in `translate()`. It also allows you to detect missing `sfence.vma`s in software by asserting that the TLB translation is the same as the uncached translation. This is not implemented in this change but we can do it in future (or you can just hack it in when needed). The detection will never be 100% but the bigger the TLB the more missing fences you will detect.
64 was chosen based on benchmarks I did last year. Performance when booting Linux keeps going up until you get to 64.

Increase TLB size to 64

---

model/riscv_insts_end.sail

- The `end` statement for `scattered enum extension` misspelled `extension`.
- `end extensionEnabled` was inadvertently dropped, and now been restored.

Fix innocuous issues with extension tagging

---

model/riscv_platform.sail

According to the priv. spec. `mtime` should be readable & writable:
> Platforms provide a real-time counter, exposed as a memory-mapped machine-mode read-write register, `mtime`.
However, the model currently does not allow writes to `mtime`. This pull requests modifies `clint_store` in order to support writes to the `mtime` memory-mapped register.

Writable mtime 

---

model/riscv_fetch_rvfi.sail
model/riscv_step_rvfi.sail
model/rvfi_dii.sail

There was some usage of the old bitfield syntax in the RVFI files that had been missed. This updates it to the new syntax to avoid the deprecation warning.

Update more old bitfield syntax

---

Makefile
c_emulator/riscv_platform.c
c_emulator/riscv_platform.h
c_emulator/riscv_platform_impl.c
c_emulator/riscv_platform_impl.h
c_emulator/riscv_sim.c
handwritten_support/riscv_extras.lem
handwritten_support/riscv_extras_sequential.lem
model/riscv_insts_zicbom.sail
model/riscv_insts_zicboz.sail
model/riscv_platform.sail
model/riscv_sys_control.sail
model/riscv_sys_regs.sail
model/riscv_termination_rv64.sail
model/riscv_types.sail
ocaml_emulator/platform.ml
ocaml_emulator/platform_impl.ml
ocaml_emulator/riscv_ocaml_sim.ml

Note that Zicbop (prefetch hints) does not need to be implemented because all it does is label some existing base instructions as prefetch hints.
~~Also I have not wired up the enable flags to the emulators because it is rather tedious (and will hopefully be replaced by riscv-config at some point).~~

Implement Zicbom, Zicboz (cbo.flush, cbo.inval, cbo.zero)

---

c_emulator/riscv_config.h
c_emulator/riscv_prelude.c
c_emulator/riscv_prelude.h
c_emulator/riscv_sim.c
model/prelude.sail
model/riscv_step.sail
ocaml_emulator/platform.ml
ocaml_emulator/riscv_ocaml_sim.ml

See: https://github.com/riscv/sail-riscv/issues/526
An extra newline is inserted after each 'step' in the simulator, if the appropriate trace option is provided. The spaces that were previously in the trace were just an artifact of an extra space inserted when we flushed the trace output (which just happened to coincide with the step). These should actually be guaranteed to delimit each instruction.
Supports both the OCaml and C emulators. For the C emulator this is enabled with `--trace=step`, and for OCaml `-trace-delimit-step`. It works slightly differently in both cases, because of how the two emulators handle the toplevel loop differently - but care was taken to ensure if you did run the sail `loop` function in C, it will behave the same.
The C simulator `--trace` option had it's …

Add an option to delimit instructions in the trace

---

model/prelude.sail
model/riscv_insts_mext.sail
model/riscv_insts_vext_arith.sail
model/riscv_insts_vext_fp_utils.sail
model/riscv_insts_vext_mem.sail
model/riscv_insts_vext_utils.sail
model/riscv_insts_vext_vset.sail
model/riscv_vext_regs.sail

Sail has built-in support for `2 ^`, and this is the only exponent we use so there's no need for the more generic `int_power`. Additionally the type of `int_power` is both way looser than `2 ^` (which is understood at the type level), and actually wrong, e.g. it will let you do `3 ^ -1` and give the result as 3.
Note I had to add spaces because this was required until a very recent Sail version - see https://github.com/rems-project/sail/issues/657

Remove int_power and use built-in 2 ^

---

Makefile
model/prelude.sail
model/riscv_fetch.sail
model/riscv_fetch_rvfi.sail
model/riscv_insts_vext_arith.sail
model/riscv_insts_vext_fp.sail
model/riscv_insts_vext_fp_red.sail
model/riscv_insts_vext_fp_vm.sail
model/riscv_insts_vext_mask.sail
model/riscv_insts_vext_mem.sail
model/riscv_insts_vext_red.sail
model/riscv_insts_vext_utils.sail
model/riscv_insts_vext_vm.sail
model/riscv_step.sail
model/riscv_vext_regs.sail

This adds explicit `var` keywords where they were missing before, and enables the `--strict-var` flag to prevent us from missing them out in future. Implicit `var` was a mistake inherited from ASL.

Add explicit vars and enable --strict-var

---

model/prelude.sail
model/riscv_platform.sail
model/riscv_softfloat_interface.sail
model/riscv_sys_control.sail
model/riscv_sys_regs.sail

Add `pure`/`impure` annotations and remove some duplicate function declarations.

Fix all Sail compilation warnings

---

Makefile
README.md

Use the new `--require-version` flag to set the minimum version to 0.18 (the current latest release). If you have an older version that supports this flag you'll get an error like
Sail version 0.17.1 is older than requested version 0.18
Currently there actually aren't any older versions that support this flag (unless you compiled from source) so you'd get this error instead:
sail: unknown option '--require-version'.
Not ideal, but the problem will solve itself eventually so I don't think it's worth worrying about for now.

Require Sail version 0.18

---

Makefile
model/riscv_xlen.sail
model/riscv_xlen64.sail

The motivation for this is that it makes deriving CHERI constants (field widths etc.) which vary between RV32 and RV64 a lot easier.

Derive xlen values from a logarithmic constant

---

model/riscv_sys_control.sail

The condition checks whether it's possible for a mode other than machine mode to take interrupts, but just because it can't, that doesn't mean we can never call this function while in another mode.
In particular, this causes a crash if you run with S mode disabled but U mode enabled, then mret to U mode without NExt.

Remove incorrect privilege assert

---

model/prelude.sail
model/riscv_insts_vext_arith.sail
model/riscv_insts_vext_fp.sail
model/riscv_insts_vext_fp_vm.sail
model/riscv_insts_vext_mask.sail
model/riscv_insts_vext_utils.sail
model/riscv_insts_vext_vm.sail
model/riscv_vext_regs.sail

A few refactorings to the vector extension:
- Sail 0.18 contains the vector_init primitive, to make initialising vectors with defined values easier. We can use this in some places where the vector code was creating an uninitialised vector, only to then initialise it later.
- Second, we can remove some uses of undefined by refactoring slightly how `init_masked_result` is used, which has the added benefit of making the mask immutable.
- Sail's pattern completeness checker is now smarter than before, so some wildcard cases in matches can also be safely removed without causing any warnings.
- We can also remove some asserts by adding an overload for the default division operator for the positive cases where truncating division and the SMT solver's euclidian division are the same, so the type …

Vector: Remove now unnecessary uses of undefined

---

model/riscv_insts_vext_mask.sail

There are some vector instructions that use `init_masked_result_cmp` but do not use the returned result variable, so just discard it rather than create a new variable.
I didn't spot these in my previous re-factoring because I was checking that what I was doing was working with Sail 0.18, but since then I've added some warnings that can catch unused variables and they flagged these two cases where part of the return value from `init_masked_result_cmp` isn't being used.

Vector: Remove some unused result variables

---

Makefile
model/riscv_csr_begin.sail
model/riscv_csr_end.sail
model/riscv_fdext_control.sail
model/riscv_insts_zicsr.sail
model/riscv_next_control.sail
model/riscv_sys_control.sail
model/riscv_sys_regs.sail
model/riscv_vext_control.sail

Resolve the strange split between `read_CSR` (which is not `scattered`) and `ext_read_CSR` (which is). Same for `write_CSR` and `is_CSR_defined`.
I changed the return type of `read_CSR` from `option(xlenbits)` to `xlenbits` since the code must already check `is_CSR_defined` before calling `read_CSR`. The only function that returned `None()` was the `seed` CSR in `write_seed_csr`, which actually meant you would get a weird "Unhandled write to CSR" if you wrote to `seed`.
I renamed & reordered the files slightly to make the scattered mapping work, but I haven't moved any of the actual definitions yet. In future we should actually scatter them.
Fixes #410

Make CSR definitions scattered

---

.github/workflows/compile.yml
Makefile
README.md

This should be a lot faster. It also means the version is pinned properly which wasn't the case before.
I also recommended users to do the same in the README do they don't have to deal with OPAM.

Install Sail from binary in CI

---

model/riscv_vmem_common.sail

With the move to Sail 0.18 this is no longer needed

Remove old Sail workaround for Virtual Memory params

---

model/riscv_insts_vext_mem.sail
model/riscv_insts_vext_utils.sail

I ran the test for VNClip and noticed that the saturation function includes logic that sets vxsat to zero. This caused the test to fail. After reviewing the Spike implementation, I found that it does not set vxsat to zero. The [spec](https://riscv-specs.timhutt.co.uk/spec/20240411/unpriv-isa-asciidoc.html#_vector_single_width_fractional_multiply_with_rounding_and_saturation) only mentions setting it to one, without specifying any case where it should be reset to zero.
> then saturates the result to fit into SEW bits. If the result causes saturation, the vxsat bit is set.
In vector instructions, if a situation causes saturation midway, vxsat is set to one but is later reset to zero. As a result, the information that vxsat was once set to one is discarded, as shown in the case in the …

Saturation remove set 0

---

model/riscv_insts_vext_mem.sail
model/riscv_next_regs.sail
model/riscv_sys_regs.sail

issues https://github.com/riscv/sail-riscv/issues/583

Merge with updates

---

model/riscv_csr_begin.sail

This was missed when menvcfg[h] was added.

Add menvcfgh to csr_name_map

---

model/riscv_freg_type.sail
model/riscv_insts_zca.sail
model/riscv_platform.sail
model/riscv_reg_type.sail
model/riscv_sys_control.sail
model/riscv_sys_regs.sail
model/rvfi_dii.sail

I left a couple where it made sense, e.g. in STORECON.
Fixes #582

Replace zero_extend(0b0) with zeros()

---

c_emulator/riscv_platform.c
c_emulator/riscv_platform.h
c_emulator/riscv_platform_impl.c
c_emulator/riscv_platform_impl.h
model/riscv_insts_vext_mem.sail
model/riscv_sys_control.sail
model/riscv_vlen.sail

Should sail-riscv use a "--isa=zvl512b_zve64d" like option in spike to implement configurable vlen and elen.
If it should I will do it.

Make VLEN and ELEN configurable and remove registers

---

c_emulator/riscv_platform.c

PR #590 added new functions to `riscv_platform.c` that omit a parameter name. While this works with newer versions of GCC, it causes an error on GCC 10 and earlier. This adds the parameter name like all of the other functions in that file to avoid breaking compatibility with older GCC.

Add parameter name to sys_vector_vlen_exp and sys_vector_elen_exp

---

c_emulator/riscv_platform.c
c_emulator/riscv_platform.h
c_emulator/riscv_platform_impl.c
c_emulator/riscv_platform_impl.h
c_emulator/riscv_sim.c

In the master branch, the N extension has been removed, but at that time, the [commit](https://github.com/riscv/sail-riscv/commit/d79e0bab7b18e0d505383b29db4fa3e76f97ab81) only removed the code in the SAIL section, ignoring the C simulator's support for the N extension (Maybe my fault) , i.e., the sys_enable_next switching function in it was not removed, so pr removed this to avoid inconsistency between the two

remove function sys_enable_next

---

model/riscv_insts_zcb.sail

Per section 29.8 of the Unprivileged ISA manual, extension Zcb requires Zca. This updates the extensionEnabled clause to capture this requirement.

Zcb requires Zca

---

Makefile
model/riscv_errors.sail
model/riscv_types.sail

This is not necessary for the model currently, however internally we wanted to use `internal_error` in a file that was before `riscv_types.sail`. Putting it in its own file makes that possible, and I think it's an organisational improvement even if the model currently does not need it.

Move Sail exception code into its own file

---

README.md
model/riscv_insts_fext.sail
model/riscv_insts_zfh.sail

Per section 24.6 of the unprivileged ISA manual:
> The Zfhmin extension includes the following instructions from the Zfh extension: FLH, FSH, FMV.X.H, FMV.H.X, FCVT.S.H, and FCVT.H.S. If the D extension is present, the FCVT.D.H and FCVT.H.D instructions are also included. If the Q extension is present, the FCVT.Q.H and FCVT.H.Q instructions are additionally included.
We already supported Zfh, so this is just a modification of some of the guards to enable only the supported instructions for Zfhmin. For now I have Zfhmin enabled whenever Zfh is enabled, but later it can be updated so that it can be enabled independently once we have better model configuration.

Add Zfhmin support

---

model/riscv_sys_regs.sail

Combine additional "with" updates per #583

Merging more with updates

---

model/riscv_sys_regs.sail

This was missed when we removed the N extension.
I'm not really a fan of this code style - in other places we explicitly copy the bits that *are* implemented using their field names, which is also not ideal but definitely better and less error prone. We should change this code to do that at some point. I added a TODO.

Zero mstatus.UPIE/UIE bits in legalize_mstatus

---

model/riscv_sys_control.sail

When the N extension was removed this code was accidentally broken because it doesn't respect mie for delegated interrupts any more.
The `internal_error`s should be unreachable, at least for the sequential output. I believe formal backends may decide `mideleg` is going to be non-zero even without S, but I think that was an existing issue.

Fix delegated interrupt handling

---

model/riscv_fdext_regs.sail
model/riscv_insts_dext.sail
model/riscv_insts_fext.sail
model/riscv_insts_vext_fp_utils.sail

Simplify the implementations with fewer intermediate variables, and fix compilation of RV64F.
I also added relevant quote from the spec because the spec for these instructions is very confusing. This is a prime candidate for getting Sail code into the spec.
Fixes #556

Fix RV64F compilation, simplify fmv implementation, and make nan boxing functions generic

---

model/riscv_sys_regs.sail

As stated in #326, the spec mentions that
>If supervisor mode is not implemented, bits SEIP, STIP, and SSIP of mip and SEIE, STIE, and SSIE of mie are read-only zeros.
Hence the change.

Fix bits SEIP, STIP, and SSIP of mip and SEIE, STIE, and SSIE of mie read-only problem

---

c_emulator/riscv_platform.c
c_emulator/riscv_platform.h
c_emulator/riscv_platform_impl.c
c_emulator/riscv_platform_impl.h
model/riscv_insts_vext_vset.sail

I don't know whether sail-riscv needs this.
The spike uses VLMAX to calculate new vl, and sail-riscv uses (AVL + 1) / 2.
The [spec](https://drive.google.com/file/d/1uviu1nH-tScFfgrovvFCrj7Omv8tFtkp/view?usp=drive_link) says:
> The number of bits implemented in vl depends on the implementation’s maximum vector
> length of the smallest supported type. The smallest vector implementation with VLEN=32
> and supporting SEW=8 would need at least six bits in vl to hold the values 0-32
> (VLEN=32, with LMUL=8 and SEW=8, yields VLMAX=32).

Make calculate new vl configurable

---

CODE_STYLE.md

Update CODE_STYLE.md to recommend using `xlen` instead of `sizeof(xlen)` to align with our current usage.

Update recommended use of xlen in CODE_STYLE

---

model/riscv_sys_control.sail
model/riscv_sys_exceptions.sail
model/riscv_sys_regs.sail

Remove pc alignment mask

---

Makefile

Optionally wrap the libs with `-Wl,-Bstatic`, `-Wl,-Bdynamic` which will enable static compilation for those libs. We don't really want to use `-static` because it statically links glibc, which is a bad idea, and also increases the binary size. Linking with a sufficiently old version of glibc is a better option.

Support static compilation of the emulator

---

Makefile
model/riscv_flen.sail
model/riscv_flen_F.sail

Similar to what was done to XLEN already, place the the types/variables that are derived from FLEN into a separate file that is always included and only leave the value of FLEN itself in the F/D specific files.

Factor out common parts of flen files

---

Makefile
model/prelude_mem.sail
model/prelude_mem_addrtype.sail
model/riscv_addr_checks.sail
model/riscv_addr_checks_common.sail
model/riscv_fetch.sail
model/riscv_fetch_rvfi.sail
model/riscv_insts_aext.sail
model/riscv_insts_base.sail
model/riscv_insts_fext.sail
model/riscv_jalr_seq.sail
model/riscv_mem.sail
model/riscv_platform.sail
model/riscv_pmp_control.sail
model/riscv_step.sail
model/riscv_sys_control.sail
model/riscv_vmem.sail

As mentioned in the #434 , using newtype to refactor the types of virtual memory and physical memory, the xlenbits type in the sail code part of the model which I think that should be virtaddrs or physaddr is refactored to correspond to the virtaddrs/physaddr type. 
Additionally, there seems to be excessive structurally similar redundant code in the memory read and write of the V extension, and I may create a simplified PR later.

use newtype to reflect address type

---

c_emulator/riscv_platform_impl.c

This matches Spike, and means a default Linux build has enough RAM to boot properly.
I'm not exactly sure why the old value was not sufficient but it didn't work when I tried and this did, and I think consistency with Spike is valuable anyway.

Increase RAM size

---

model/prelude_mem.sail
model/prelude_mem_addrtype.sail
model/prelude_mem_metadata.sail
model/riscv_platform.sail
model/riscv_sys_control.sail
model/riscv_vmem.sail
model/riscv_xlen32.sail
model/riscv_xlen64.sail

Restructure the physical address to be 34 bits in the RV32 case and 64 bits in the RV64 case. Idea from @Timmmm and @Alasdair in #615 
In the RV32 case, if sv32 is not enabled, use the Spike approach and zero-extend the virtual address to 34 bits for translation.

make physical address 34-bit in sv32

---

model/riscv_types_kext.sail

This PR updates the `aes_shift_rows_fwd` and `aes_shift_rows_inv` functions to match the versions defined in the latest vector crypto spec after this fix: https://github.com/riscv/riscv-crypto/commit/a19ae2086efcb87b6988f4510bf19cd642b16740.
These functions are not used in any scalar instructions and are not currently called anywhere, so no existing functionality should be affected, but this change is necessary for the upcoming vector crypto implementation and ensures the versions in the scalar spec match the vector crypto spec (as the Sail versions are used directly in the scalar spec).

Fix aes_shift_rows_fwd and aes_shift_rows_inv functions from latest vector spec.

---

model/riscv_platform.sail

Hi!
I have developed the ACTs (Architectural Compliance Tests) and coverage points for [RISC-V compliance verification](https://github.com/riscv-non-isa/riscv-arch-test). As part of the coverage points, I needed support for printing the MTI (Machine Timer Interrupt) value upon a hart update to improve the visibility and tracking of machine interrupts during the test execution.
To achieve this, I made a small change to one of the print functions, ensuring that the MTI value is printed whenever the hart state is updated. This change is essential for accurate compliance verification and enhances the observability of machine interrupts.
Please review and consider adding this change to the original repository for inclusion in the RISC-V architecture test suite.

fix: Print MTI value upon hart update for machine timer interrupt visibility

---

Makefile

This was missed when merging the Sstc extension.

Actually compile riscv_sstc.sail

---

Makefile
c_emulator/riscv_sail.h
c_emulator/riscv_sim.c

This appears to be an obsolete and unused mechanism of disabling extensions by calling into the model to modify `misa`. Now it is done by `sys_enable_` callbacks.

Remove obsolete z_set_Misa functions

---

README.md

#570 added support for the Sstc extension but didn’t add it to the list of supported extensions in the readme.

Add Sstc to supported extensions list

---

Makefile
model/riscv_extensions.sail
model/riscv_fdext_control.sail
model/riscv_insts_aext.sail
model/riscv_insts_base.sail
model/riscv_insts_dext.sail
model/riscv_insts_fext.sail
model/riscv_insts_mext.sail
model/riscv_insts_svinval.sail
model/riscv_insts_zba.sail
model/riscv_insts_zbb.sail
model/riscv_insts_zbc.sail
model/riscv_insts_zbkx.sail
model/riscv_insts_zbs.sail
model/riscv_insts_zcb.sail
model/riscv_insts_zcd.sail
model/riscv_insts_zcf.sail
model/riscv_insts_zfa.sail
model/riscv_insts_zfh.sail
model/riscv_insts_zicbom.sail
model/riscv_insts_zicboz.sail
model/riscv_insts_zicond.sail
model/riscv_insts_zifencei.sail
model/riscv_insts_zkn.sail
model/riscv_insts_zks.sail
model/riscv_sys_regs.sail
model/riscv_types.sail
model/riscv_vext_control.sail
model/riscv_zihpm.sail
model/riscv_zkr_control.sail

Having this distributed through the code can lead to slightly awkward dependency order issues. We need to keep it scattered though so e.g. CHERI can add its extensions.
Fixes #633

Move extension scattered enum to single file

---

Makefile

This does not seem to be a valid Sail target anymore.

Remove Makefile cgen target

---

model/riscv_vmem_tlb.sail

This Sail feature was not available when this code was written, but now we can use it to remove the duplication.

Use vector_init for TLB

---

model/riscv_sys_regs.sail

This was accidentally missed from the CBO implementation.

Allow writing CBO bits in xenvcfg

---

doc/ExtendingGuide.md
doc/ReadingGuide.md

As discussed in #660, this adds a warning to the Reading Guide and Extending Guide indicating that they are out of date. I also did some initial cleanup of the Reading Guide to fix broken links and obviously outdated information. The extending guide still needs a more extensive overhaul.

Add outdated warning to documentation and begin updating it

---

model/riscv_insts_zicbom.sail
model/riscv_insts_zicboz.sail

CBO faults report the address in rs1, not the cache block address.
The spec is not explicit about this yet but I have a pending PR to clarify that: https://github.com/riscv/riscv-isa-manual/pull/1433

Report the correct address for CBO errors

---

model/prelude.sail
model/riscv_insts_vext_arith.sail
model/riscv_insts_vext_fp.sail
model/riscv_insts_vext_fp_red.sail
model/riscv_insts_vext_fp_vm.sail
model/riscv_insts_vext_mask.sail
model/riscv_insts_vext_mem.sail
model/riscv_insts_vext_red.sail
model/riscv_insts_vext_utils.sail
model/riscv_insts_vext_vm.sail
model/riscv_vext_regs.sail

fix #554
emmm...
I will test the code with riscv-vector-tests later...
And to make sure `assert('n > 0);` is right

Remove vector of bools in vext

---

model/prelude_mem_addrtype.sail
model/riscv_insts_zicbom.sail
model/riscv_insts_zicboz.sail

try resolve #668 
Added operator overloading for `physaddr` and `virtaddr`
I think we don't need to implement `==` and `!=`? 
Because `eq_anything` (I just discovered this) has already been introduced in `prelude.sail`.
https://github.com/riscv/sail-riscv/blob/c0ebea2ff14e6a39d53161c3e51dcbabe3e9a0f1/model/prelude.sail#L17

Overload operators for physaddr and virtaddr

---

model/prelude.sail
model/prelude_mem.sail
model/prelude_mem_metadata.sail
model/riscv_addr_checks.sail

* Add `mem_access_width` type. This will also be used for PMAs in future.
* Use `mem_access_width` type for `__Write/ReadRAM_Meta` instead of existential.
* Move `max_mem_access/width` to `prelude.sail`. This helps with compile dependency ordering for future PMA support.

Add mem_access_width type

---

model/riscv_sys_control.sail

Split the privilege level checking and read-only checking into separate functions. This is slightly neater and also helps CHERI where ASR permissions need to use `check_CSR_priv()`.

Split check_CSR_access up

---

model/riscv_flen.sail
model/riscv_flen_D.sail
model/riscv_flen_F.sail
model/riscv_insts_fext.sail

Use Sail's fancy dependent types instead of separate functions for each float load/store size. Functionality is unchanged.

Simplify float load/store

---

model/riscv_vmem_pte.sail

```diff
-                            Read()          => false,
+                            Read(_)         => false,
```
I don't know why the previous one could compile, it should be wrong, but after replacing `ext_access_type` with newtype, the compiler detected the error correctly.
```
union AccessType ('a : Type) = {
Read      : 'a,
Write     : 'a,
ReadWrite : ('a, 'a),
Execute   : unit
}
```

Fix match AccessType

---

model/riscv_zicntr_control.sail

Per discussion in #658, the unprivileged counters/timers (`time`, `cycle`, `instret`) do not depend on U mode being available. They exist in any implementation that includes the Zicntr extension.
Fixes #684

Unprivileged counter CSRs do not depend on U mode

---

model/riscv_fetch.sail
model/riscv_insts_aext.sail
model/riscv_insts_base.sail
model/riscv_insts_fext.sail
model/riscv_insts_vext_mem.sail
model/riscv_insts_zicboz.sail
model/riscv_mem.sail
model/riscv_platform.sail
model/riscv_sys_control.sail
model/riscv_vmem.sail

resolve part of #433
Use `result` type instead of `MemoryOpResult`，for `MemoryOpResult`, `MemValue` is `'a`, so I think it's ok to use `type`
But `PTW_Success` has five members, I did not include it in this PR, I think we should create a struct for it?
```ocaml
union PTW_Result('paddr : Type, 'pte : Type) = {
PTW_Success: ('paddr, 'pte, 'paddr, nat, bool, ext_ptw),
PTW_Failure: (PTW_Error, ext_ptw)
}
```

Use result type instead of MemoryOpResult

---

model/riscv_platform.sail

The memory segments are hard-coded into `within_phys_mem` anyway and its log messages.  A more general map would need a better API to the C emulator.

Remove unused attempt at a platform memory map.

---

model/riscv_fdext_regs.sail
model/riscv_sys_control.sail
model/riscv_sys_regs.sail
model/riscv_vext_regs.sail

As mentioned in #639, and there are also some legitimacy issues in legalize_mstatus, so this PR is intended to help make corrections

refactor mstatus handler function

---

model/riscv_types.sail

`report_invalid_width` is unused as of #680 and seems to be a remnant from issues with an earlier version of the compiler.

Remove unused report_invalid_width function

---

model/riscv_mem.sail
model/riscv_platform.sail

`sail_zero_extend` is aliased to `zero_extend`, and `zero_extend` is already used in most places

Replace uses of sail_zero_extend with zero_extend

---

model/riscv_csr_begin.sail
model/riscv_csr_end.sail

`csr_name` had been moved because of a bug in the Sail compiler. Seems like this is no longer an issue so move it back to where it is supposed to be.

Move csr_name function back to desired location

---

model/riscv_sys_regs.sail

Per section 3.1.8 of the priv spec, `medeleg` is a 64 bit register and `medelegh` accesses the upper 32 bits on RV32.

Make medeleg 64 bits and add medelegh

---

model/riscv_insts_base.sail
model/riscv_sys_control.sail
model/riscv_sys_regs.sail
model/riscv_types.sail
model/riscv_vmem.sail

First three patches of https://github.com/riscv/sail-riscv/pull/683.

Minor architecture cleanup

---

c_emulator/riscv_sail.h
c_emulator/riscv_sim.c
model/main.sail
model/riscv_ext_regs.sail
model/riscv_fdext_regs.sail
model/riscv_pmp_control.sail
model/riscv_regs.sail
model/riscv_step.sail
model/riscv_step_ext.sail
model/riscv_step_rvfi.sail
model/riscv_sys_control.sail
model/riscv_sys_regs.sail
model/riscv_vmem.sail
model/riscv_vmem_tlb.sail

This simplifies, clarifies and fixes the reset functionality.
Until now the model conflates reset and initialisation, and does way more than it should on reset. The RISC-V spec only requires a very small number of things to be reset.
This change:
1. Renames the `init` functions to `reset`, to clarify that they correspond to resetting the chip.
2. Removes the `ext_init` and `ext_rvfi_init` functions. The latter is not used and the former is only used by the old CHERI code.
3. Removes the reset of the X and F registers. These are non-reset.
4. Removes the reset of various CSRs that are non-reset (`mip`, `mie`, `mideleg`, `mtvec`, `mepc`, etc).
5. Adds reset of `mstatus[MIE]` and `mstatus[MPRV]`. As far as I can see they were missing.
6. Add one-time init of `mhartid` etc to 0.
I didn't …

Refactor chip reset

---

model/riscv_sys_regs.sail

SPP is read-only zero if supervisor mode is not implemented.

Fix mstatus.SPP legalisation

---

model/riscv_insts_zicsr.sail

While here, remove an unused mapping intended for the assembly clause.

Fix a corner case in zicsr: avoid a read-effect in CSRRW when rd is 0.

---

c_emulator/CMakeLists.txt

When doing a default installation, CMake fails when it tries to install the unbuilt targets:
```
CMake Error at c_emulator/cmake_install.cmake:60 (file):
file INSTALL cannot find "/build/source/build/c_emulator/riscv_sim_rv32f":
No such file or directory.
```
Make all targets optional to avoid the failure;  this will install only the targets that are built.

c_emulator: fix cmake install with unbuilt targets

---

CMakeLists.txt
model/CMakeLists.txt

In my build sail is installed to a custom prefix that I pass to CMake via `CMAKE_PREFIX_PATH` instead of by overriding `$PATH`. Fix the one place in the build where we were using a bare sail instead of `${SAIL_BIN}`.

Fix building the model when the sail binary is not in $PATH

---

model/riscv_fdext_regs.sail
model/riscv_sys_regs.sail
model/riscv_vext_regs.sail

I'm not sure why we didn't think of this before, but you can have the SD field positioned relative to xlen, so it's at 63 on RV64 and 31 on RV31. This simplifies the code a lot.
Note #683 has an alternative solution that just calculates SD on read, but I'm not sure we need that after this simplification. In any case we can still do it if desired.

Simplify mstatus[SD] bit handling

---

model/riscv_insts_base.sail

Another patch from the mstatus cleanup,  https://github.com/riscv/sail-riscv/pull/683#issuecomment-2621133329.

insts_base: ignore architecture in SFENCE_VMA

---

model/riscv_insts_vext_arith.sail
model/riscv_insts_vext_fp.sail
model/riscv_insts_vext_fp_red.sail
model/riscv_insts_vext_fp_vm.sail
model/riscv_insts_vext_mask.sail
model/riscv_insts_vext_mem.sail
model/riscv_insts_vext_red.sail
model/riscv_insts_vext_vm.sail
model/riscv_insts_vext_vset.sail
model/riscv_vext_control.sail

https://github.com/riscv/sail-riscv/pull/623

Refactor vstart assignments to use set_vstart function

---

c_emulator/riscv_sim.c

Add some missed CLI options to help, and remove obsolete 'P' option removed in 4de2bff1.

Fix emulator help message.

---

Makefile.old
README.md
model/CMakeLists.txt
model/riscv_extensions.sail
model/riscv_sscofpmf.sail
model/riscv_zihpm.sail

This adds the `mhpmeventNh` and `scountovf` CSRs. It also fixes `mhpmevent` to be 64 bits instead of `xlenbits` (though this mistake is unobservable without Sscofpmf).
Since the model doesn't ever actually increment any of the HPM counters yet, there is no need to actually implement the filtering logic or the overflow interrupt. If/when we add some example HPM sources we will need to do that.

Implement Sscofpmf (counter overflow and privilege mode filtering)

---

model/riscv_vmem_tlb.sail

A slight bug in the latest virtual memory rewrite: virtual addresses were zero extended in the TLB instead of sign extended, which meant that `sfence.vma` sometimes wouldn't match the TLB entries it should.
This was found after further internal testing. The failing test passes after these changes.

Fix TLB address matching for sfence.vma

---

Makefile.old
README.md
c_emulator/riscv_sim.c

resolve #727 
- remove all `#ifdef ENABLE_SPIKE`
- remote `init_spike()`, `init_check()`, `compare_states()`
- remove things about linked to Spike in README and Makefile

Remove support for linking C emulator to Spike

---

model/riscv_mem.sail
model/riscv_platform.sail
model/riscv_sys_regs.sail

These were missed when we removed the deprecated effects annotations.

Remove obsolete comments about effect annotations

---

c_emulator/riscv_sim.c

The new CMake testing infrastructure assumed (one might say logically!) that `riscv_sim_..` would exit with a non-zero exit code if a test failed. That actually wasn't the case, so in fact we haven't been testing anything.
This corrects that. Fortunately all the tests still pass.

Fix simulator exit code

---

model/prelude.sail
model/riscv_insts_base.sail
model/riscv_xlen.sail

Refactor some of the base `execute` clauses to remove intermediate variables and unnecessary `if`s. The motivation for this is to make them read a bit better when included in the ISA manual.
1. Make `shift_right_arith` generic so you don't need a 32/64-bit version.
2. Use `rs1_val` in fewer places - it's actually longer than `X(rs1)` anyway.
3. Directly assign to `X(rd)` where possible.
4. Avoid single letter variables.

Simplify some base instruction execute clauses

---

CMakeLists.txt
README.md
build_simulators.sh

This downloads the latest release of GMP and builds it as part of the overall emulator build. This should make it easier to build sail without having to install system dependencies.
See https://github.com/riscv/sail-riscv/issues/215

Add a DOWNLOAD_GMP option to build against a local GMP build

---

model/riscv_pmp_control.sail

Inline `pmpCheckPerms` and use `== Machine` instead of `match`. I think this is a lot easier to understand, and shorter.

Simplify PMP code

---

model/riscv_step.sail
model/riscv_sys_regs.sail
model/riscv_zicntr_control.sail

The previous code switched between explicit updates to all 64 bits of `minstret` and automatically incrementing it via a `minstret_increment` boolean. Unfortunately that doesn't work for RV32 where you can write to one half of the 64-bits *and* the other half is still automatically incremented.
This change fixes that, so the writes to each half are stored until after the automatic increment, and then applied.
Note the behaviour for this is not well specified in the ISA manual (see https://github.com/riscv/riscv-isa-manual/issues/1255) however this seems like the most plausible interpretation and it is what Spike implements and it makes sense.
Tested via some internal testing and this directed test sequence (which also passes on Spike):
```
csrw minstreth, zero
csrw minstret, zero
nop # …
```

Fix minstreth behaviour

---

model/riscv_sys_regs.sail

Fixes a warning about missing initialisation here.

Fix missing initialisation for minstret[h]_write

---

sail_runtime/CMakeLists.txt

This header isn't used, and I plan to remove it from the Sail release.

Remove unused header from sail_runtime/CMakeLists.txt

---

.github/workflows/compile.yml
.github/workflows/release.yml
CMakeLists.txt
Makefile.old
README.md
c_emulator/CMakeLists.txt
model/CMakeLists.txt

There are a whole lot of other small improvements to make once we bump to 0.19 (enabling the theorem provers in CI, when guards for encdec, etc.), but I figured I’d start with the dependency simplification since building the model has been such a big focus lately.

Bump required sail compiler version to 0.19 and remove zlib dependency

---

model/riscv_insts_aext.sail
model/riscv_insts_base.sail
model/riscv_insts_vext_mem.sail

These changes align with the general LOAD and STORE implementation pattern used elsewhere in the codebase.

Refactor `vext_mem` remove redundant type annotations and simplify

---

test/first_party/CMakeLists.txt

This is quite useful information for debugging. Note this will print `...clang;--target=riscv32` (i.e. semicolon separated instead of space separated), but I think it's not worth adding the code to get "correct" output.

Print compiler used for tests

---

model/riscv_sys_regs.sail

A recent PR against the isa manual (https://github.com/riscv/riscv-isa-manual/pull/1864) clarified that mstatus SIE and SPIE should be read-only zero when S mode is not supported. While updating, I noticed several other bits that should also be guarded by this constraint according to the spec.

Update mstatus bits guarded by privilege modes

---

test/first_party/src/common/link.ld

It seems like lld and ld interpret linker scripts slightly differently. `lld` would put `.bss.mmio` in `if_mmio`, and then when you put `.stack` in `if_ram` it would sensibly reset put it at the start of `if_ram`. However `ld` is a bit dumber and just continues in `if_mmio` leading to overflow.
`ld` also requires manually skipping to the start of `if_ram`, otherwise it tries to allocate starting at 0.
Fixes #799

Fix linker script for GNU ld

---

c_emulator/riscv_sim.cpp

caused by #748
Forgot to assign `val` to `inst_limit` after parsing cli params

Fix --inst-limit

---

model/riscv_insts_zicbom.sail

The bitwise check of xenvcfg.CBIE to check whether cbo.inval was enabled was incorrect, since CBIE is a four-valued setting. Specifically, it decoupled the bits in the reserved value 0b10 of CBIE.
This fixes the handling of the reserved value, and also throws an internal error when it is detected to indicate a possible bug in xenvcfg legalization.
The privilege check should extend to the hypervisor case, when two different illegal exceptions could be thrown.  This check as written doesn't match the pseudo-Sail in the CMO spec, but is arguably clearer.
I've left the CBCFE handling alone, since it works for the single bit case.
I'd like to make sure that the handling of no S-mode case is correct (the pseudo-Sail in the spec doesn't seem to handle it explicitly).

Improve Zicbom implementation.

---

.clang-format
c_emulator/CMakeLists.txt
c_emulator/riscv_sim.cpp
c_emulator/rvfi_dii.cpp
c_emulator/rvfi_dii.h

This unclutters the main simulator code considerably.
Tested with TestRig to ensure no regressions using 
```
./utils/scripts/runTestRIG.py -a manual -b manual  --implementation-A-port 8080 --implementation-B-port 8081
```
@arichardson Are there other RVFI invocations I should test?

Move most of RVFI code into its own file.

---

CMakeLists.txt

Not all compilers default to C++17, so we need to tell CMake to request c++17 (for std::optional).
Fixes https://github.com/riscv/sail-riscv/issues/812
Needed since https://github.com/riscv/sail-riscv/pull/784

Explicitly request C++17 support

---

model/riscv_insts_zicsr.sail

Split out from and sitting atop #617, the last commit here is the salient one.  This transforms a `bool * regidx` under one `ast` data constructor into two `ast` data constructors, allowing us to stop punning between `regidx` and `bits(5)`.  This will be significant in light of #617 for supporting the E extension, where `regidx` will be (isomorphic to) `bits(4)`; see #646.

Simplify Zicsr AST

---

model/riscv_insts_zvbb.sail
model/riscv_sys_control.sail

While here, also fix an indentation for vstart.
It looks like this is a hole in the vector test suite.

Ensure V context is dirtied in Zvbb instructions.

---

handwritten_support/RiscvExtras.lean

Fixes a termination error in the Lean translation of the function `extensionEnabled`.

Lean: refine sizeOf instance for extension type

---

model/riscv_pmp_control.sail
test/first_party/CMakeLists.txt
test/first_party/src/test_max_pmp.c

This fixes a bug if you set `pmpaddr` to `ones()`. For NAPOT it would return `(zeros(), zeros())`. For NA4 it would return `(ones(), zeros())`. In both cases it will match no addresses, whereas it should match all memory, or the top 4 bytes respectively.
A test is included for NAPOT that fails before and passes afterwards.
Fixes #739

Fix incorrect behaviour with INT_MAX pmpaddr

---

README.md
model/CMakeLists.txt
model/prelude.sail
model/riscv_extensions.sail
model/riscv_insts_zcmop.sail
model/riscv_insts_zimop.sail

Extracted and updated the `Zimop` and `Zcmop` extensions from #377.
One of the tricky parts with this extension is that it is designed to have its instructions overridden by other extensions (like `Zicfiss`). The implementation in #377 had a function dedicated to Zimop and Zcmop in each of their files that listed which specific instructions were overridden. I'd rather avoid the need to modify this file each time a new extension is added that reuses one of its encodings, so I added new scattered `encdec_overrides` and `encdec_compressed_overrides` mappings for this purpose. These mappings are checked first, and only if there is no match does it check the normal `encdec` mappings. This allows each new extension (like `Zicfiss` and `Zicflp`) to be self-contained. It also opens the door to …

Implement Zimop and Zcmop Extensions

---

model/riscv_insts_vext_vset.sail

Vector tail agnostic and vector mask agnostic operands are mandatory for `vsetvli` and `vsetivli`.
Resolves #489

Mandatory vsetvli and vsetivli operands

---

c_emulator/riscv_sim.cpp

Seems to be remnants from earlier versions of this file.

Remove unused code from riscv_sim.cpp

---

CMakeLists.txt
coq-sail-riscv.opam
handwritten_support/CMakeLists.txt
handwritten_support/riscv_extras.v
model/CMakeLists.txt

This includes changing the prover name from Coq to its new name Rocq, updating the opam package file, adding a couple of built-in functions to the handwritten portion, and building the resulting Rocq code.  The output is all gathered in one rocq build directory to keep the namespace manageable and convenient.
It also drops the extra `_variant` from the name of lem/rmem/rocq output, which is rather redundant.
This pull request doesn't include CI.  That will come later once I've sorted out some reasonable caching to avoid rebuilding Rocq too often (or avoid it entirely).

Add cmake support for Rocq

---

.github/workflows/compile.yml
CMakeLists.txt
c_emulator/CMakeLists.txt
c_emulator/riscv_platform.cpp
c_emulator/riscv_platform.h
c_emulator/riscv_platform_impl.cpp
c_emulator/riscv_platform_impl.h
c_emulator/riscv_sim.cpp
config/CMakeLists.txt
config/default.json
config/default_config.h.in
model/CMakeLists.txt
model/riscv_insts_vext_vset.sail
model/riscv_platform.sail
model/riscv_sys_regs.sail
model/riscv_vlen.sail
sail_runtime/CMakeLists.txt
test/first_party/CMakeLists.txt
test/riscv-tests/CMakeLists.txt

This is the first in a series of PRs (and probably patches to this PR) aiming to replace the ad-hoc C stubs used for configuration with a Sail-native configuration system using a separate configuration file. This is a draft PR as it needs a new release of Sail to work.
This PR is split into two commits:
1. The first simply updates the CMake build system to include the Sail JSON handling code, and adds a simulator option to pass a configuration file but does not change the model code whatsoever. The file config/default.json is added to store all the default configuration options (but is empty in this commit). I took the `-c` short option away from the sail coverage option, as it isn't even built in by default.
2. The second replaces the existing options in the simulator. The only behaviour …

Replace ad-hoc model configuration with Sail-native configuration

---

config/default.json
test/first_party/CMakeLists.txt

Somehow the config changes got through CI without this breakage being detected. Alasdair added a `jq` based system to allow tests to have modified configs, but it wasn't being used for the PMP test which needs PMPs to be enabled (by default they weren't).
I'm not totally convinced by the `jq` approach and to avoid the immediate need to add `jq` everywhere and learn how its filters work I just change the default config to enable PMPs.
I also fixed a couple of missing `DEPENDS`.

Fix PMP test

---

model/riscv_vmem.sail
model/riscv_vmem_pte.sail

This has caught us (Codasip) out before. One could make the argument that a leaf PTE is a pointer to a physical address. Renaming it to `pte_is_non_leaf` removes any ambiguity.

Rename pte_is_ptr to pte_is_non_leaf for clarity

---

model/CMakeLists.txt
model/arithmetic.sail
model/prelude.sail
model/riscv_insts_zbc.sail
model/riscv_insts_zvbc.sail

Make the `reverse` function more generic; add a helper for carryless multiply and use it in the appropriate scalar and vector instructions.
Tested against upstream `riscv-tests` and the vector test suite.

Improvements to prelude

---

model/prelude_mem.sail
model/prelude_mem_addrtype.sail
model/riscv_addr_checks.sail
model/riscv_insts_base.sail
model/riscv_mem.sail
model/riscv_platform.sail
model/riscv_pmp_control.sail
model/riscv_step.sail
model/riscv_sys_control.sail
model/riscv_vmem.sail

As discussed in #779, this makes `Physaddr` and `Virtaddr` consistent with `Regidx`. The type is lowercase and the constructor is capitalized.

Capitalize Physaddr and Virtaddr constructors

---

model/prelude.sail
model/riscv_insts_zicsr.sail

For some reason there was a `zeros` overload, but it wasn't used.

Remove unused zeros overload

---

Makefile.old
model/arithmetic.sail
model/riscv_insts_zbc.sail

Also define a SMT property to prove equivalence with the previous implementation.
Update the Makefile.old to use the check_properties target to test the property with Z3, pending CMake integration.
Fixes #824.

Define a reverse carry-less multiply function for cmulr instructions.

---

README.md
c_emulator/riscv_platform.cpp
c_emulator/riscv_platform.h
c_emulator/riscv_platform_impl.cpp
c_emulator/riscv_platform_impl.h
c_emulator/riscv_sim.cpp
model/prelude.sail

Per discussion at today's meeting, this adds a command line switch to enable unratified/experimental extensions. Each unratified extension should also have its own enable switch using the standard config system, so enabling an unratified extension will require both enabling it in the configuration file and passing the `--enable-experimental` flag.

Add enable-experimental flag for unratified extensions

---

model/riscv_insts_zicbom.sail

These permission checks were not respecting `mstatus[MPRV]` (modify privilege).

Use correct effective privilege for cbo.clean/inval

---

model/riscv_step.sail
model/riscv_sys_regs.sail
model/riscv_zicntr_control.sail
test/first_party/src/test_minstret.S

This reverts commit cd54a3780178d8cf3ca0fa29009fa7f14059e014.
It hasn't been clarified in the ISA manual, but it has been clarified in [this Github issue](1) and in a new test in `riscv-tests` that the original behaviour was expected.
Essentially there are two different concepts: architectural CSRs (the instruction counter) and CSR addresses `minstret`, `minstreth`. The ISA manual conflates these concepts. When it says
> an explicit CSR write suppresses and overrides any implicit writes or modifications to the same CSR by the same instruction.
When it says CSR here it means the architectural CSR, not the CSR address.
I tested this against the new `instret_overflow` test in `riscv-tests`.
[1]: https://github.com/riscv/riscv-isa-manual/issues/1255
Fixes #832

Revert "Fix minstreth behaviour"

---

.github/workflows/compile-lean.yml

The Lean backend is still relatively unstable and it's hard to fix errors for people that aren't familiar with it. This changes it to only be run manually so it doesn't block other changes.
When it's more stable we can re-enable it.

Only run Lean CI manually

---

.github/workflows/compile.yml

Display the output of failing tests in CI to make debugging easier.

Display test output for failing tests in CI

---

config/default.json

As discussed in the golden model meeting, this should allow the default configuration to pass all of the riscv-tests.
Fixes #841

Enable misaligned accesses in default config for riscv-tests

---

model/riscv_pmp_control.sail
test/first_party/CMakeLists.txt
test/first_party/src/common/crt0.S
test/first_party/src/test_max_pmp.c
test/first_party/src/test_pmp_access.c

In a recent refactor I accidentally removed the * 4 factor in `pmpaddr` registers. This fixes that.
I added a basic test that tests this at least for the NAPOT case. We could do with a more comprehensive test but it's quite difficult to write this sort of test as an ELF. I think maybe this is a situation where unit tests would be appropriate.
Finally I added a missing `sfence.vma` in the `test_max_pmp.c` test (doesn't actually matter for the Sail model but we should be correct), and simplified `crt0.S`'s full match PMP address.
Fixes #850

Fix PMP address matching

---

README.md
config/default.json
model/CMakeLists.txt
model/riscv_extensions.sail
model/riscv_insts_vext_utils.sail
model/riscv_insts_zvknhab.sail
model/riscv_zvk_utils.sail

Add following instructions:
```
vsha2ms.vv
vsha2ch.vv
vsha2cl.vv
```
Tested with [riscv-vector-tests](https://github.com/chipsalliance/riscv-vector-tests).

Add support for Zvknha and Zvknhb extensions

---

CMakeLists.txt

This tells CMake that we've tested it up to version 3.31 so it can enable newer policies that are available in versions up to that point and not warn us about them.
Fixes #818. Tested with CMake 4 and `./build_simulators.sh`.

Add cmake_policy

---

model/riscv_vmem.sail
model/riscv_vmem_pte.sail

The specification has a numbered list of steps in the algorithm. The Sail version had implemented access permission checks (Steps 6,8) before the superpage alignment check (Step 5).  This commit fixes the ordering.
There is currently no functional difference between the two orders: all the steps involved raise page-faults corresponding to the access type; the only difference would be the error printed in the execution log.
However, when shadow stack is implemented, it inserts a Step 7 that could raise an access-fault exception that would make the difference in step order visible.
While here, mark in comments the steps of the algorithm for easier correlation with the prose spec.
Also tested with a successful Linux boot.

More closely align address translation with the specification.

---

.github/workflows/compile-lean.yml
.github/workflows/compile.yml
.github/workflows/release.yml
.github/workflows/test-results.yml
.pre-commit-config.yaml
CODE_STYLE.md
CONTRIBUTING.md
README.md
config/default.json
doc/ExtendingGuide.md
doc/ReadingGuide.md
os-boot/README.md
test/README.md
test/riscv-tests/README

Primarily added for formatting json files, but also formats markdown and yaml.
I noticed #866 makes significant formatting changes to the `default.json` config file. It probably makes sense to have an auto formatter that is enforced in CI for JSON files (especially as I expect we will add more preset configs as time goes on) to make changes easier to review going forward, similar to what we already do with `clang-format`. Prettier seems like one of the more popular JSON formatters, so I went with that. By default, it also formats Markdown and YAML files, but if we'd rather, I can disable that and only do the JSON files.

Add prettier pre-commit hook

---

model/prelude_mem_addrtype.sail
model/riscv_fetch.sail
model/riscv_fetch_rvfi.sail
model/riscv_insts_aext.sail
model/riscv_insts_base.sail
model/riscv_jalr_seq.sail
model/riscv_mem.sail
model/riscv_vmem.sail

part of #779
Currently I retained other similar functions (`bool_to_bits`, (int) `to_bits`, `exceptionType_to_bits` ...). They seems good for the readability, and also make it easier to goto definitions.

Add overload bits_of for virtaddr_bits and physaddr_bits

---

model/riscv_insts_vext_mem.sail
model/riscv_insts_vext_utils.sail

Try to simplify some type constraints of ext_v
- Created a new type, `type nf_t = range(1, 8)`(any naming suggestions?), which can save a lot of type constraints like `0 < nf <= 8`
- Removed some type declarations that can be inferred automatically
There are still a few exceptions where nf_t cannot be used
1. One is that the spec restricts the optional values of `nf`
> Only NFIELDS values of 1, 2, 4, 8 are supported, with other values reserved.
> [31.7.9. Vector Load/Store Whole Register Instructions](https://riscv-specs.timhutt.co.uk/spec/20240411/unpriv-isa-asciidoc.html#_vector_loadstore_whole_register_instructions)
```
val process_vsre : forall 'f 'b 'n, ('f in {1, 2, 4, 8}) ...
```
2. Another is that we need `'q` to mark the size
So I created a `type nf_v('q) = 'q > 0 & 'q <= 8` …

[Ext_V] Simplily nf type constrains

---

.github/workflows/rocq.yml
model/riscv_termination.sail

The termination measures should be fine (although I wish I had a nice way to generate most of these...)
The CI is based on a standard Rocq Docker image and uses the Sail release binary like the main CI job.  I suppose it could be made a job within the main workflow, but I think a separate workflow is better because it can be easily disabled if it causes trouble.

Update Rocq termination information and add CI

---

.github/workflows/rocq.yml

#864 was merged after #868, but without the changes from #868 merged into it, so it passed the CI from that branch but failed CI once merged into master. This fixes the precommit errors with it.

Fix precommit failure

---

model/riscv_insts_zfa.sail

These don't appear to be register indices which is what `rs1` implies so I renamed it to `constantidx`, which is also consistent with the `assembly` and `execute` clauses.

Rename Zfa `rs1` to `constantidx`

---

model/CMakeLists.txt

This commit enables the use of termination measures by the Lean backend.

Add termination measures to the Lean backend

---

config/default.json

Fixes #193. This parameter controls how many instructions need to complete for the cycle CSR to increment. While this is implementation defined (and likely not constant even within a given implementation), a default of 2 seems a lot more natural than 100.

Change default instructions_per_tick to 2

---

model/riscv_insts_base.sail
model/riscv_insts_zba.sail
model/riscv_insts_zbb.sail
model/riscv_insts_zbc.sail
model/riscv_insts_zbkb.sail
model/riscv_insts_zbkx.sail
model/riscv_insts_zbs.sail
model/riscv_insts_zca.sail
model/riscv_insts_zcb.sail
model/riscv_insts_zfa.sail
model/riscv_insts_zicbom.sail
model/riscv_insts_zicboz.sail
model/riscv_insts_zicond.sail
model/riscv_jalr_rmem.sail
model/riscv_jalr_seq.sail
model/riscv_types.sail

Pretty straightforward cleanup.

Remove redundant RISCV_ prefixes on internal ast nodes and enums.

---

c_emulator/riscv_sim.cpp

It was not handled correctly (unlike '-h'), resulting in a confusing `No elf file provided.` message before the help text.

Fix the '--help' option.

---

model/riscv_platform.sail
model/riscv_step.sail
model/riscv_step_common.sail
model/riscv_sys_regs.sail
model/riscv_types.sail

* Simplify the `stepped` code. It is equivalent to whether or not the model ends in an active state, so we can just return that.
* Simplify handling of `minstret_increment`.
* Change `step_no` to `nat`.
* Remove unused `exit_wait` parameter from `run_hart_active()`.
* Change `instbits` to 32-bit instead of xlenbits.

Refactor try_step() some more

---

config/default.json
model/riscv_extensions.sail
model/riscv_sys_regs.sail

From #796 , as the spec say
>Implementations are not required to support all MODE settings, and if satp is written with an unsupported MODE, the entire write has no effect; no fields in satp are modified.
so adding extensionenabled and applying guard in legalize_satp I think might work.

Add satp mode guard

---

model/riscv_platform.sail
model/riscv_sys_regs.sail

Not sure why I didn't think of this when reviewing #880. This inlines the initialization of the machine info registers, similar to what we do for several other registers throughout the model. These values are set at model initialization time.

Inline machine info register initialization

---

.github/workflows/rocq.yml

There are still occasional bugs in the backend that are blocking PRs being merged.
See https://github.com/riscv/sail-riscv/pull/862#issuecomment-2839700728

Make Rocq workflow run on request.

---

c_emulator/riscv_platform.cpp
c_emulator/riscv_platform.h
c_emulator/riscv_platform_impl.cpp
c_emulator/riscv_platform_impl.h
c_emulator/riscv_sim.cpp
handwritten_support/RiscvExtras.lean
handwritten_support/riscv_extras.lem
handwritten_support/riscv_extras.v
model/riscv_platform.sail

If htif is disabled
- cpp doesn't enforce check on the elf `tohost` symbol
- sail disallow reading and writing to tohost
If the elf does not meet the requirements, sail can at least try to run it instead of exit directly

Disable htif when tohost symbol not found

---

README.md
config/default.json
model/riscv_extensions.sail

Also add Svbare to the config and README as a supported extension.

Fix Svbare warning.

---

README.md
config/default.json
model/CMakeLists.txt
model/arithmetic.sail
model/riscv_extensions.sail
model/riscv_insts_vext_utils.sail
model/riscv_insts_zvksh.sail
model/riscv_zvk_utils.sail

Add following instructions:
```
vsm3me.vv
vsm3c.vi
```
Tested with [riscv-vector-tests](https://github.com/chipsalliance/riscv-vector-tests).

Add support for Zvksh extension

---

model/CMakeLists.txt

This was not included when moving over to the CMake build system and resulted in a kernel panic when trying to boot linux (#889)

Add missing riscv_sstc.sail to CMake build

---

build_simulators.sh

This file does not depend on any bash features, we can use POSIX sh.

build_simulators.sh: use /bin/sh

---

model/riscv_extensions.sail
model/riscv_termination.sail

Change the structure of the measure for `currentlyEnabled` to make the base extensions (A, B, C, D, M, ...) have measure 0 and the generic case be 1, so that adding an extension is hopefuly less likely to break terminiation checking if it only depends on these basic extensions.

Fix termination measure again, try to make it more rubust to change

---

model/prelude.sail
model/riscv_fdext_regs.sail
model/riscv_vmem_tlb.sail

Unfortunately I had to rename it to trunc, but I think this is still better.
Partially fixes #898 
Better name suggestions welcome! @Alasdair FYI; I don't know if you have a plan for breaking changes to the standard library at some point but maybe add this to the list!

Make truncate infer its length

---

.github/workflows/compile.yml

Turns out the `merge_group` hook is required for CI jobs that are supposed to run in the merge queue. Otherwise the queue will just wait for the job to complete but never actually start it.

Update CI to run in merge queue

---

model/riscv_insts_vext_utils.sail

Sail needs to give some of the implicit arguments to Lean because they are not deducible from the type of the arguments.

Fix compilation of the Lean backend

---

c_emulator/CMakeLists.txt
c_emulator/riscv_callbacks.cpp
c_emulator/riscv_callbacks.h
c_emulator/riscv_prelude.cpp
c_emulator/riscv_prelude.h
model/CMakeLists.txt
model/prelude.sail
model/riscv_callbacks.sail
model/riscv_fdext_regs.sail
model/riscv_insts_vext_mem.sail
model/riscv_insts_vext_vset.sail
model/riscv_insts_zicsr.sail
model/riscv_mem.sail
model/riscv_pc_access.sail
model/riscv_regs.sail
model/riscv_sys_control.sail
model/riscv_types.sail
model/riscv_vext_control.sail
model/riscv_vext_regs.sail
model/rvfi_dii.sail

Add a callback API for register, PC and CSR updates, memory writes and traps. This is used for logging and RVFI instead of embedding that code in the model itself.

Implement callbacks for state-changing events

---

Makefile.old
config/default.json
doc/ReadingGuide.md
model/CMakeLists.txt
model/riscv_insts_aext.sail
model/riscv_insts_base.sail
model/riscv_insts_fext.sail
model/riscv_insts_vext_mem.sail
model/riscv_mem.sail
model/riscv_termination.sail
model/riscv_vmem_utils.sail

Refactor the LOAD and STORE instruction so they split misaligned
accesses into multiple sub-accesses and perform address translation
separately. This means we should handle the case where a misaligned
access straddles a page boundary in a sensible way, even if we don't
yet cover the full range of possibilities allowed for any RISC-V
implementation.
There are options for the order in which misaligned happen, i.e. from
high-to-low or from low-to-high as well as the granularity of the splitting,
either all the way to bytes or to the largest aligned size. The splitting
can also be disabled if an implementation supports misaligned accesses in hardware.
In addition tidy up the implementation in a few ways:
- Very long lines on the LOAD encdec were fixed by adding a helper
- Add some linebreaks …

 Handle address translation for misaligned loads and stores better

---

model/riscv_callbacks.sail
model/riscv_fdext_regs.sail
model/riscv_vext_regs.sail

This should fix the builds for the the non-C backends.

Add empty stubs for the state-change callbacks

---

c_emulator/riscv_platform.cpp
c_emulator/riscv_platform.h

We compile the model as C, and unlike C++, in C prior to C23 a function declaration with no parameters didn't mean that it was a function with no parameters; instead it meant it was a function with unknown parameters, so any would be allowed.
This was fixed in C23 and GCC 15 increased the minimum standard to C23, thus exposing this mistake.

Fix build failure due to plat_enable_htif signature mismatch

---

.github/workflows/compile.yml
c_emulator/CMakeLists.txt
sail_runtime/CMakeLists.txt

Unfortunately since a Sail compiler binary for Mac is not yet available this uses OPAM. Once one is available we'll switch to that.
This also fixes a dependency ordering error on all platforms - `sail_runtime` depends on GMP but this wasn't declared so it could fail if you didn't have GMP already available (i.e. you were building it from source).

Fix macOS compilation and add to CI

---

Makefile.old
README.md
config/default.json
model/CMakeLists.txt
model/riscv_extensions.sail
model/riscv_insts_vext_utils.sail
model/riscv_insts_zvkned.sail
model/riscv_zvk_utils.sail

Implements the Zvkned (NIST Suite: Vector AES Block Cipher) extension, as of version [Release 1.0.0](https://github.com/riscv/riscv-crypto/releases/tag/v1.0.0).
The following instructions are included:
- vaesef.[vv,vs]
- vaesem.[vv,vs]
- vaesdf.[vv,vs]
- vaesdm.[vv,vs]
- vaeskf1.vi
- vaeskf2.vi
- vaesz.vs
All instructions were tested with VLEN=128 and results were compared with QEMU results of each instruction.
Note
This PR was originally developed by @charmitro , and now the Vector AES Block Cipher has been released.

Add support for Zvkned.

---

.github/workflows/compile.yml
model/riscv_insts_vext_mem.sail
model/riscv_sys_regs.sail
model/riscv_types.sail
model/riscv_vmem_utils.sail

Define `vmem_{read,write}` to work with this width type, and update width types in relevant signatures.
Add rv32f and rv64f to CI build.
Fixes #936.

Define and use a width type for memory widths.

---

CMakeLists.txt

On CMake >= 3.24 with the `DOWNLOAD_GMP` the build would fail if you didn't have `makeinfo` installed. This fixes that.
Fixes #934.

Don't require makeinfo to build GMP

---

model/riscv_sys_regs.sail

Add missing `mstatush` to the `csr_name_map` mapping. This was causing incorrect CSR log messages.

Add mstatush to csr_name_map

---

config/default.json
model/riscv_insts_base.sail

From section 12.2.1 of the priv spec:
> For implementations that make satp.MODE read-only zero (always Bare), attempts to execute an SFENCE.VMA instruction might raise an illegal-instruction exception.

Add config option to trap on sfence.vma if virt mem not supported

---

.github/workflows/compile-lean.yml

Now that we have a "ci_pass" job, we can reenable the Lean CI job for each PR but not add it as a dependency of that job. This way, we will know if Lean is broken by a new change and can hopefully get it fixed without bogging down developers who aren't familiar with the theorem prover backends.

Add Lean back to CI for each PR but don't require it to pass

---

CMakeLists.txt

Check if CMP0135 is supported by the version of CMake being used before setting it. If it isn't supported, the old behavior is used anyway.
Fixes #947.

Prevent build failures with CMake versions < 3.24.

---

model/riscv_insts_zcf.sail
model/riscv_sys_regs.sail

When any compressed extension is supported (whether enabled or not), `xepc[1]` can be written.
When compressed instructions are disabled, `xepc[1]` is read as 0.
Both of these were checked based on `misa[C]`, but compressed instructions can be supported without setting `misa[C]` (e.g. an `RV32IF_Zca` hart).

Fix xepc interaction with compressed extensions

---

c_emulator/riscv_callbacks.cpp
c_emulator/riscv_callbacks.h
c_emulator/riscv_config.h
c_emulator/riscv_prelude.cpp
c_emulator/riscv_prelude.h
c_emulator/riscv_sim.cpp
model/prelude.sail
model/riscv_callbacks.sail
model/riscv_regs.sail

Add option to print abi or architectural register names in trace and disassembly

---

model/CMakeLists.txt
model/riscv_insts_zaamo.sail
model/riscv_insts_zalrsc.sail

Zaamo and Zalrsc are separate extensions (even if both are included in A), so by our convention they should be in separate files. They also have suprisingly little overlap, so it is a very clean split.

Split the Zaamo and Zalrsc extensions into separate files

---

model/arithmetic.sail
model/riscv_insts_vext_fp_utils.sail
model/riscv_insts_vext_utils.sail
model/riscv_insts_zbb.sail

Use the existing bit counting functions, and add `count_ones()`.
One downside is that `count_leading_zeros()` is not implemented in Sail, so it makes the inclusion in the ISA manual less helpful.
However given the difficulties of actually getting Sail code into the ISA manual it's probably ok for now. Also `count_leading_zeros()` is a standard operation and has obvious semantics.

Use existing bit counting functions

---

model/main.sail
model/riscv_platform.sail
model/riscv_sys_regs.sail

This checks the value at runtime to avoid surprises when config values are silently truncated.

Use to_bits_checked() for config values

---

model/riscv_sys_regs.sail

Also simplify the definitions a little. I used `{1, 2, 4, 8}` for `get_sew_bytes()` because I think it's only coincidentally the same as `is_mem_width()`, and also it's shorter and easier to read.

Fix to_bits_unsafe() for vector length registers

---

model/prelude.sail
model/riscv_insts_zvbb.sail

This delegates the bits versions to the integer versions. This also identified a dangerous looseness in the types - previously you could use the bit version to shift by any amount, and it would give the wrong results if the shift was more than `'n`.
In Zvbb we have to use `2 ^ SEW_pow` instead of `get_sew()` so that Sail knows the link between `SEW` and `SEW_pow`.

Fix uses of to_bits_unsafe for bit rotate and Zvbb

---

c_emulator/riscv_callbacks.cpp

This is seemingly a silly copy-paste typo from 90de2d05.
Example of erroneous logs:
```
[0] [M]: 0x0000000000210868 (0xF4068CD3) fmv.h.x fs9, a3
x25 <- 0xFFFFFFFFFFFF463F
```
Here `x25` should be `f25`.

Use correct register prefix in `freg_write_callback`

---

model/riscv_fetch.sail
model/riscv_fetch_rvfi.sail
model/riscv_insts_zaamo.sail
model/riscv_insts_zicbom.sail
model/riscv_insts_zicboz.sail
model/riscv_vmem.sail
model/riscv_vmem_utils.sail

last part to resolve #433 
Same with #872, retained two ext_ptw `result(('paddr, ext_ptw), ('failure, ext_ptw))` now

Use result type for TR_Result instead of union

---

config/default.json
model/riscv_extensions.sail
model/riscv_fdext_control.sail
model/riscv_insts_zicsr.sail
model/riscv_sys_regs.sail
model/riscv_vext_control.sail
model/riscv_zicntr_control.sail
model/riscv_zihpm.sail

As mentioned in #849, the spec states that the Zicsr extension is Extension for Control and Status Register (CSR) Instructions. Therefore, the encdec sections of the AST CSRReg and CSRImm are guard with a `when` condition to achieve this purpose.

Make Zicsr extension configurable

---

test/first_party/src/common/runtime.c

fix #944 
Passing va to ... is invalid, but I didn't find an offical doc

Fix printf in first party test

---

model/riscv_insts_zcb.sail

Per The RISC-V Instruction Set Manual, Volume I: Unprivileged Architecture, Version 20250508, the assembly syntax for `c.sh` is:
```
c.sh rs2', uimm(rs1')
```
But, the Sail code has (edited for brevity):
```
"c.sh" ^ spc() ^ creg_name(rs1c) ^ sep() ^ (uimm) ^ "(" ^ creg_name(rs2c) ^ ")"
```
Reverse the fields in the Sail code to match the spec.

fix: c.sh has operands reversed

---

model/riscv_insts_zca.sail

Per The RISC-V Instruction Set Manual, Volume I: Unprivileged Architecture, Version 20250508, the assembly syntax for `c.sh` is:
```
c.sd rs2', offset(rs1')
```
But, the Sail code has:
```
"c.sd" ^ spc() ^ creg_name(rsc1) ^ sep() ^ creg_name(rsc2) ^ sep() ^ hex_bits_8(uimm @ 0b000)
```
Reverse the fields in the Sail code to match the spec.
Note also that syntax described by the Sail expression would be:
```
c.sd rs1',rs2',uimm
```
So, fix that to match the spec, also, in several places.

fix: c.sw,c.sd have assembly operands reversed, missing parens

---

model/riscv_insts_zfa.sail

Per The RISC-V Instruction Set Manual, Volume I: Unprivileged Architecture, Version 20250508, 25.4 Modular Convert-to-Integer Instruction:
> The assembly syntax requires the RTZ rounding mode to be explicitly
> specified, i.e., `fcvtmod.w.d rd, rs1, rtz`.
But, the Sail code does not accept that third "rtz" operand.
Add the explicit third operand to `fcvtmod.w.d`.

fix: fcvtmod.w.d requires explicit "rtz"

---

model/riscv_insts_base.sail

Per The RISC-V Instruction Set Manual, Volume I: Unprivileged Architecture, Version 20250508, A.3.6 Fences, the syntax is:
```
FENCE.TSO
```
Further, in 2.7 Memory Ordering Instructions:
> A FENCE.TSO instruction is encoded as a FENCE instruction with
> fm=1000, predecessor=RW, and successor=RW.
Simplify the FENCE_TSO implementation to exactly as described in the spec.

fix: fence.tso has no operands

---

model/riscv_fdext_regs.sail
model/riscv_regs.sail
model/riscv_types.sail

I was going to change these functions to a mapping, but I think we don't really need them at all.
I also removed some redundant `assert()`s for invalid register numbers.

Remove regidx_to_regno functions etc.

---

c_emulator/CMakeLists.txt
c_emulator/config_utils.cpp
c_emulator/config_utils.h
c_emulator/riscv_sim.cpp

This helps re-use from other files that might need it.

Move the `get_config_` function out of `riscv_sim.cpp`.

---

README.md
config/default.json
model/CMakeLists.txt
model/arithmetic.sail
model/riscv_extensions.sail
model/riscv_insts_zvkg.sail

Add following instructions:
```
vghsh.vv
vgmul.vv
```
Tested with [riscv-vector-tests](https://github.com/chipsalliance/riscv-vector-tests).

Add support for Zvkg extension

---

c_emulator/riscv_sim.cpp

`ULLONG_MAX` is defined in `climits`, so it should be explicitly included.
Ran into a build failure with an older compiler without this include. I think sometimes `iostream` includes it, but we shouldn't rely on that.

Include climits in riscv_sim.cpp

---

.github/workflows/compile-lean.yml

Before this change, we skipped sail build & install when hitting the `.opam` cache. As a result, some random partially outdated sail version was used, instead of the intended latest tip-of-tree of sail. This PR continues to cache opam and sail, but does not skip the sail build & install on a cache hit, but executes them, trusting that the cache will accelerate them. As a result, we get the best of both worlds, fast builds and always the latest sail version.

Lean CI: use the latest version of sail

---

model/riscv_insts_base.sail
model/riscv_insts_zaamo.sail
model/riscv_insts_zalrsc.sail

This would previously have printed `.aq.rl` whereas the correct assembly is `.aqrl`.
Fixes #995.

Fix handling of .aqrl in assembly mapping

---

c_emulator/riscv_callbacks.cpp

Seems like this was just forgotten. The vector callback prints the value in hex but doesn't prefix if with `0x` like all of the other callbacks.

Add 0x prefix to vector callback printed value

---

model/riscv_insts_zawrs.sail

This was missing. I verified that GAS accepts both of these and it doesn't accept just `wrs`.

Add assembly for WRS instructions

---

model/riscv_insts_vext_arith.sail
model/riscv_insts_vext_vm.sail

These instructions were printing signed immediates as unsigned numbers, which leads to errors when assembling them with GAS like
Error: bad value for vector immediate field, value must be -16...15

Fix signed immediates in vector assembly

---

model/riscv_device_tree.sail
model/riscv_extensions.sail
model/riscv_insts_end.sail

- Add the `riscv,isa-base` and `riscv,isa-extensions` properties, and make the value of `riscv,isa` more accurate.
- Introduce an extensionName mapping for extensions, and use it in ISA string generation.
- Add a formatting enum for generation that could be extended for other formats of the ISA string.
- While here, do a minor cleanup of `riscv_extensions.sail` to fix ordering and comments.
Fixes #992.

Generate more accurate ISA information for device tree.

---

model/riscv_insts_vext_mask.sail

The RISC-V Instruction Set Manual Volume I: Unprivileged Architecture (Version 20250508), section 30.15.2. "Vector count population in mask `vcpop.m`" says:
> This instruction previously had the assembler mnemonic `vpopc.m` but was
> renamed to be consistent with the scalar instruction. The assembler
> instruction alias `vpopc.m` is being retained for software compatibility.
Use the preferred mnemonic.

fix: incorrect mnemonic for "vcpop.m"

---

model/riscv_insts_zcb.sail

Compressed source registers have two conventions:
- "rsc1"/"rsc2"
- "rs1c"/"rs2c"
Given that the latter convention is confined to just `model/riscv_insts_zcb.sail`, change it there to match the rest.

fix: unify naming of compressed source registers

---

model/riscv_insts_zca.sail
model/riscv_insts_zcd.sail
model/riscv_insts_zcf.sail
model/riscv_regs.sail

Assembly for load/store instructions need a base register in the form:
```
instruction destination,offset(base)
```
Within that set, stack-based instructions need to explicitly specify
the stack pointer (even though it is ignored in encoding).
Also, `fsd`, `fsw` have reversed operands.

fix: Correct a few compressed load/store assembly

---

model/riscv_insts_base.sail
model/riscv_insts_zbb.sail

* Use `log2_xlen` for bit rotation and shift amounts.
* Minor formatting.

Simplify Zbb execute clauses

---

model/riscv_regs.sail

Instead of having a totally new map, delegate to the main register name map. This also means that compressed register names will respect `get_config_use_abi_names()`.

Delegate compressed register name map

---

model/riscv_zvk_utils.sail

Switch some `int`s that are never negative to `nat`. This will allow future improvements to the `%` operator.

Use `nat` in Zvk utils

---

model/riscv_insts_zvbb.sail

These instructions were missing checks that the EEW (`SEW_widen`) is not greater than 64. The spec states:
> The V extension supports EEW of 8, 16, and 32, and 64.
And also
> Note: If Zve32x is supported then Zvkb or Zvbb provide support for EEW of 8, 16, and 32. If Zve64x is supported then Zvkb or Zvbb also add support for EEW 64.
So eventually we will need to make this configurable, but it never supports >64 bits anyway.

Add missing SEW_widen checks for Zvbb

---

model/riscv_insts_mext.sail

These are unnecessary and also erase important type checking information.

Remove int annotations from M extension

---

model/prelude.sail
model/riscv_insts_mext.sail

Change `s` (signed) to `is_unsigned`. This removes the need for `maybe_not_u` and `bool_not_bits` and it's clearer.
Also add a `negate` that I missed.

Invert signed bool for M extension

---

model/riscv_insts_mext.sail

Rename `rs1_val` to `rs1_bits` to make the difference from `rs1_int` clearer, and `q`, `r` to `quotient`, `remainder`. No changes in functionality.

Rename some variables in the M extension

---

model/riscv_platform.sail
model/riscv_sys_regs.sail

When `menvcfg.STCE` is unset, `mip.STIP` is only writable by M-mode software.   `menvcfg.STCE` needs to be set for `mip.STIP` to reflect the timer interrupt from `stimecmp`.

Fix a bug in `clint_dispatch()`.

---

c_emulator/riscv_platform.cpp
c_emulator/riscv_platform.h
handwritten_support/RiscvExtras.lean
handwritten_support/RiscvExtrasExecutable.lean
handwritten_support/riscv_extras.lem
handwritten_support/riscv_extras_sequential.lem
model/riscv_insts_zalrsc.sail
model/riscv_sys_control.sail

I've previously used this to inject sprurious Store-Conditional failures, however it required some tweaking because it's called very early before various exceptions can happen.
A better solution is to spuriously cancel the reservation directly in `load_reservation()` or by calling `cancel_reservation()`.
This change doesn't actually do that but I added notes explaining that you can. In future when we provide a library interface we can do it like that.

Remove speculate_conditional

---

model/riscv_insts_vext_mem.sail

The whole register vector load/store instructions should use `lmul` in the assembly mnemonic, not `seg...`.
Fixes #1085.

Fix vector load/store whole registers instructions assembly

---

model/riscv_platform.sail
model/riscv_smcntrpmf.sail

These will be affected by the Sdext extension and hence need to belong to a common file.
This also fixes #783.

Move the functions guarding `mcycle` and `minstret` increments to `riscv_platform`.

---

c_emulator/riscv_sim.cpp
model/riscv_step.sail

For Sdext, `try_step` will also need to return whether the hart entered debug mode (i.e. halted) or experienced an error in debug mode.  The `stepped` case will then hold if nothing unusual happened (e.g. is not waiting and not in debug mode).
This is a step towards the API for Sdext.

Make `try_step` return whether the hart is waiting, instead of whether it stepped.

---

model/riscv_insts_zvbb.sail

The encoding of `vror.vi` wasn't entirely correct, as it lacked the top bit of the 6 bit immediate.
This would lead to illegal instruction exceptions for immediates in range [32,64).

Fix vror.vi immediate encoding

---

model/CMakeLists.txt

`--strict-bitvector` actually affects type checking so we need to use it for every command, otherwise we can get type errors with some backends and not others.

Use the same --strict flags for all Sail commands

---

model/riscv_insts_zba.sail

Remove some unnecessary intermediate variables. Add trailing commas.

Minor Zba style improvements

---

model/riscv_insts_vext_vset.sail
model/riscv_sys_regs.sail
model/riscv_vext_control.sail

The spec says that `vstart` is XLEN bits wide so this changes the underlying value to `xlenbits`. This allows removing various `zero_extend()`s. It still only allows writing the lowest VLEN_pow bits.

Change register bit-width of vstart from 16 to xlen

---

model/prelude.sail
model/riscv_device_tree.sail
model/riscv_insts_vext_fp_red.sail
model/riscv_insts_vext_fp_utils.sail
model/riscv_insts_vext_mem.sail
model/riscv_insts_vext_utils.sail
model/riscv_mem.sail
model/riscv_platform.sail
model/riscv_sys_regs.sail
model/riscv_vext_regs.sail
model/riscv_zvk_utils.sail

This changes the definition of `%` and `/` to *only* work with positive numbers and also require the divisor to be non-zero.
The very few number of places that need signed division can call `quot_round_zero`/`rem_round_zero` directly. These don't require positive arguments, but they do still require a non-zero divisor.
Making this change required updating a load of other code which didn't have sufficiently accurate types, so it's a quite a large commit but not easy to split up.

Improve typing of division and modulo

---

config/rv32d.json
config/rv64d.json
model/riscv_pmp_control.sail
model/riscv_pmp_regs.sail
model/riscv_validate_config.sail

This adds config flags to allow marking PMP address matching modes as not supported. If software tries to write an unsupported mode it will get set to OFF instead.
For NA4 mode it is required that the grain G is 0. If it isn't then that mode is unsupported. This is also checked in `config_is_valid()` which is redundant... but I think that's ok for now. Another option would be to print a warning like `Warning: NA4 is marked as supported but G > 0 so it has been disabled`.
Fixes #1109

Add config flags to control PMP address mode support

---

c_emulator/config_utils.cpp
c_emulator/riscv_sim.cpp
c_emulator/rvfi_dii.cpp

Minor clean up, replaced hardcoded exit codes (0/1) with EXIT_SUCCESS and EXIT_FAILURE for better readability

Replace exit codes with EXIT_SUCCESS/EXIT_FAILURE constants

---

model/riscv_fdext_regs.sail
model/riscv_insts_zcd.sail
model/riscv_insts_zcf.sail

Add `newtype cfregidx` so that we don't need to use `cregidx` for compressed floating point register indices.
Fixes #1052

Use newtype cfregidx for compressed floating point register indices

---

model/CMakeLists.txt

Test the SMT Sail properties. I verified the test fails if a property is incorrect by manually breaking one of them. This test takes about 30s to run.

Test SMT properties in CI

---

model/riscv_insts_zba.sail
model/riscv_insts_zcb.sail
model/riscv_types.sail

The shift amount for these instructions is pretty clearly part of the opcode, so we can decode it directly and avoid so much repetition. The only slightly awkward part is that a shift of 0 is not allowed for `ZBA_RTYPE`. That's handled with `when shamt != 0b00`.

Reduce duplication in Zba

---

CMakeLists.txt

When building libgmp from source, enable position independent code. This isn't strictly necessary right now, but if you want to build the Sail model as a shared library then you do need this, and in general position independent code causes fewer annoying linking problems.

Build libgmp as position independent code

---

model/riscv_csr_begin.sail
model/riscv_fdext_control.sail
model/riscv_insts_zicsr.sail
model/riscv_pmp_regs.sail
model/riscv_smcntrpmf.sail
model/riscv_sscofpmf.sail
model/riscv_sstc.sail
model/riscv_sys_exceptions.sail
model/riscv_sys_regs.sail
model/riscv_vext_control.sail
model/riscv_vmem.sail
model/riscv_zicntr_control.sail
model/riscv_zihpm.sail
model/riscv_zkr_control.sail

This enables data-dependent illegal instruction traps on CSR writes, such as on out-of-bounds values for vstart.
Indicating other kinds of traps would need a bigger refactor, but this should suffice for now.

Allow `write_CSR` to indicate an illegal instruction trap.

---

c_emulator/riscv_callbacks.cpp

This fixes #1094, where CSR values were incorrectly logged as 64-bit when running in RV32 mode.

Fix CSR trace output to print correct width based on XLEN

---

model/main.sail

using isla-sail on the current RISC-V model is broken, because `init_model` now takes a string, but the call to `init_model` in `isla_footprint` only passes unit. fix this by passing the empty string (isla doesn't support loading configuration files at runtime, as far as I understand. Therefore it will anyway always use the default config).

adapt isla_footprint to the init_model signature change

---

README.md
config/rv32d.json
config/rv64d.json
model/riscv_extensions.sail
model/riscv_insts_zaamo.sail
model/riscv_regs.sail
model/riscv_termination.sail
model/riscv_types.sail

Add the Zacas extension that introduces the following instructions:
- amocas.w for RV32 and RV64
- amocas.d for RV32 and RV64
- amocas.q for RV64 only
Tested with these tests: https://github.com/riscv-non-isa/riscv-arch-test/tree/dev/riscv-test-suite/rv64i_m/Zacas/src

Add Zacas (atomic compare and swap) extension

---

.github/workflows/compile.yml
CMakeLists.txt
c_emulator/CMakeLists.txt
c_emulator/riscv_sim.cpp
c_emulator/sail_riscv_version.cpp.in
c_emulator/sail_riscv_version.h
cmake/project_version.cmake

The project version is retrieved using a `--version` option.
The build info is retrieved using `--build-info`. This currently shows the Sail and C++ compiler versions, and the git info for sail-riscv if available.

Add a project version and build information to the simulator.

---

model/riscv_pmp_regs.sail

According to the spec, an implementation can implement 0, 16 or 64 PMP entries, which is controlled by `sys_pmp_count`. One entry consists in one `pmpaddr` register and 8 bits of configuration.
Therefore, there should be 0, 4 or 16 `pmpcfg` registers, as each hold 4 configuration entries. However, if `sys_pmp_count` is 16 the current Sail model defines 16 `pmpaddr` and 16 `pmpcfg` registers, i.e. there are more configurations than there are `pmpaddr`.
0 PMP entries -> 0 `pmpaddr`, 0 `pmpcfg`
16 PMP entries -> 16 `pmpaddr`, 16 `pmpcfg` <-- the problem is here
64 PMP entries -> 64 `pmpaddr`, 16 `pmpcfg`
This fixes the model to have 4 `pmpcfg` registers in that case.

Fix number of defined `pmpcfg` CSRs

---

dependencies/softfloat/berkeley-softfloat-3/README.md

GitHub did not render README.txt or README.html, so this adds a README.md.

Add README.md for berkeley-softfloat-3 library

---

model/riscv_csr_begin.sail
model/riscv_csr_end.sail
model/riscv_fdext_control.sail
model/riscv_pmp_regs.sail
model/riscv_smcntrpmf.sail
model/riscv_sscofpmf.sail
model/riscv_sstc.sail
model/riscv_sys_control.sail
model/riscv_sys_exceptions.sail
model/riscv_sys_regs.sail
model/riscv_vext_regs.sail
model/riscv_vmem.sail
model/riscv_zicntr_control.sail
model/riscv_zihpm.sail
model/riscv_zkr_control.sail

Instead of having special extra functions to check accessibility of CSRs that depend on the privilege mode, and `is_write`, just add those parameters to `is_CSR_defined` (and rename it to `is_CSR_accessible`).
This also fixes a bug (discovered by inspection when making this change) - the `check_Counteren` was not checking the `...h` registers for RV32.

Move privilege-based CSR access into scattered is_CSR_accessible function

---

model/riscv_insts_vext_vset.sail

The `vset[i]vli` instructions take an immediate that sets the `vtype` CSR. The normal way to generate the immediate value is by giving values for all of `vtype`'s fields (`ma`, `ta`, `sew` and `lmul`).
`sew` and `lmul` have reserved values, however that does *not* mean that instructions that use those reserved values are necessarily reserved. Implementations are allowed to legalise the values (see the note in `handle_illegal_vtype()`).
Therefore we should support disassembling these instructions. The syntax for a `vset[i]vli` with a reserved `vtype` is just to use an integer immediate instead of the mnemonics.

Support generating assembly for reserved vtypes

---

model/CMakeLists.txt
model/riscv.sail_project

Use the Sail module system to organise the files in the model. Rather than passing a list of files on the command line, the files are specified using the `model/riscv.sail_project` file.
The previous version uses a big flat list of files which is unwieldy and hard to understand as it is not clear immediately what the high level structure of the model is, and the way we configure the model does not allow for extensions to easily be added and removed without hand-modifying the CMake. This doesn't matter for the C backend but it does for formal/SV backends.
To solve this problem, I have added a basic module system to Sail, which allows for the structure of the specification to be specified as a collection of modules in a `.sail_project` file. The key ideas here are as follows:
- Each of …

Add sail_project file to modularise the specification

---

model/CMakeLists.txt

Through various previous simplifications this had devolved into the for-switch antipattern. We can remove the for loop and simply execute things in sequence.

Simplify model/CMakeLists.txt by removing `variant`

---

test/CMakeLists.txt
test/README.md

Update Sail RISC-V Tests URL and version to use the official https://github.com/riscv-software-src/sail-riscv-tests repository. 
The new Sail RISC-V Tests release adds two tests covering LMUL=8 for widening reduction instructions.

Update Sail RISC-V Tests download URL

---

model/riscv_insts_vext_arith.sail
model/riscv_insts_vext_fp.sail

This call to `read_vmask()` always returns `ones()` so we can use that directly instead.

Simplify vector code when calling read_vmask

---

dependencies/softfloat/berkeley-softfloat-3/build/Linux-x86_64-GCC/platform.h

I'm not sure exactly why softfloat is set up like this, but with `INLINE` only defined as `inline`, then it was possible in debug builds to get undefined references to some of the inlined functions (e.g. `softfloat_countLeadingZeros32`). Apparently in C99 `inline` functions *might* not actually get emitted; you need to use `static inline`. I don't fully understand why but ChatGPT called this "The C99 Inline Mess" when I asked about it so probably not worth digging!
The old version of `platform.h` also used `static inline`.

Fix softfloat debug builds

---

model/riscv_insts_vext_arith.sail

NISTYPE and NITYPE instructions need to use zero-extended immediates, not sign-extended  ones.
For #1071.

Fix immediate signedness bug in NISTYPE/NITYPE

---

model/prelude.sail
model/riscv_freg_type.sail
model/riscv_platform.sail
model/riscv_reg_type.sail
model/riscv_step.sail
model/riscv_sys_control.sail
model/riscv_types.sail

There was only one place where we used `bit_str()` so this overload is not very useful.

Remove `BitStr()`, `bit_str()` and use native `bits_str()` instead

---

c_emulator/riscv_sim.cpp

An empty `std::string` does not return a `nullptr` on `.c_str()`.  This bug would lead to:
```
$ ./build/c_emulator/sail_riscv_sim --validate-config
Configuration in  is valid.
```

Fix validation message.

---

README.md
c_emulator/riscv_callbacks.cpp
c_emulator/riscv_callbacks.h
c_emulator/riscv_callbacks_if.h
c_emulator/riscv_callbacks_log.cpp
c_emulator/riscv_callbacks_log.h
c_emulator/riscv_callbacks_rvfi.cpp
c_emulator/riscv_callbacks_rvfi.h
config/rv32d.json
config/rv64d.json
doc/ChangeLog.md
model/riscv_regs.sail
model/riscv_sys_control.sail
model/riscv_sys_regs.sail
model/riscv_types.sail

Allow configuring `regidx` to be 4 bits instead of 5, so only 16 `x` registers are supported. Instruction encodings to access `x16` - `x31` are reserved and will cause an illegal instruction exception if `E` is enabled.

Support for the E base architecture

---

c_emulator/riscv_prelude.cpp
c_emulator/riscv_prelude.h
model/prelude.sail
model/riscv_platform.sail
model/riscv_step.sail
model/riscv_sys_control.sail

The config flags `config_print_instr` and `config_print_platform` are checked twice in the Sail and C code. This commit removes the C functions `print_instr()` and `print_platform()`, and replaces them with a single function `print_trace()`, which doesn't do a redundant check.
Fixes #1174

Remove duplicate config_print checks

---

.github/workflows/run-full-tests.yml
.github/workflows/run-riscv-tests.yml

Adds a PR label check to the run-full-tests workflow so that it can be run on PRs by adding the `run-full-tests` label.
This is primarily intended for PRs that make significant changes to vector so that the full vector suite can be run before merging.

Run full testsuite on PRs with `run-full-tests` label

---

model/riscv_vmem_pte.sail

By converting the bits to bools up-front we can massively simplify the expressions.

Simplify check_PTE_permission

---

model/riscv_insts_vext_mem.sail

Since none of the argument or return types are linked they can all be expressed without `forall`, which is a lot simpler.
Fixes #1194

Simplify riscv_insts_vext_mem's function signatures

---

model/riscv_addr_checks.sail

This accidentally became unused when `jump_to` was added, however there is currently no difference between `ext_control_check_addr` and `ext_control_check_pc` in the latest implemented CHERI spec (0.9.3), and in the latest draft spec this check has been removed entirely.

Remove unused  `ext_control_check_addr` hook function.

---

model/riscv_addr_checks.sail
model/riscv_addr_checks_common.sail
model/riscv_mem.sail

These seem to be unused in both the CTSRD and Alliance CHERI models.

Remove unused `ext_check_phys_mem_{read,write}` hooks.

---

model/riscv_types.sail
model/riscv_vmem_pte.sail

This separates the two checks - first for read/write permissions and second for privilege level. It's arguably makes the code more complex but I think it's easier to see the actual logic and also will be probably simpler once we add more access types (AMOs, LR/SC, jump table fetch, etc.)

 Split PTE privilege and access checks

---

config/CMakeLists.txt

The package build broke since it was looking in the source directory for the generated config files.

Fix location of generated configs for install.

---

model/riscv_sys_regs.sail

This is discovered during testing with spike. When the V extension is disabled in the configuration, running the `csrrs reg sstatus VS_MASK` instruction, spike does not set the VS field, but sail does

Make {m,s}status[VS] read-only zero when Ext_V not supported

---

handwritten_support/RiscvExtras.lean
handwritten_support/RiscvExtrasExecutable.lean
handwritten_support/riscv_extras_sequential.lem

Many of the old handwritten_support function definitions are no longer used now that the config system is in place.

Remove unused definitions from handwritten_support files

---

.github/workflows/compile-lean.yml
.github/workflows/compile.yml

Reduces macOS CI time by ~10 minutes.
We were caching the opam Sail install for Lean builds already, but not for the macOS standard CI jobs.

Cache macOS Sail Install

---

README.md
config/config.json.in
doc/ChangeLog.md
model/riscv.sail_project
model/riscv_extensions.sail
model/riscv_insts_zicbop.sail
model/riscv_zicbop_types.sail

Add prefetch hint instructions. The Sail model has no caches so this has no effect on execution, however it does make the disassembly output more useful and show what the encoding should be.

Add Zicbop extension

---

c_emulator/config_utils.cpp
c_emulator/config_utils.h

Add support for reading bit vectors as well as integers. This will be needed in future to read the address that we should write the DTB (Device Tree Binary/Blob) to.

Make get_config_uint64 more flexible

---

.github/workflows/release.yml
doc/ChangeLog.md
model/CMakeLists.txt

This bundles the Sail unit tests as well, not sure it's worth excluding those.
The generated html and json are separate for now; it might be more convenient that way.
Fixes #1265.

Add html doc bundle to build and release.

---

handwritten_support/RiscvExtras.lean
handwritten_support/RiscvExtrasExecutable.lean
handwritten_support/riscv_extras.lem

The `sys_enable_experimental_extensions` function was not added to the handwritten files for the theorem provers.
This fixes the Lean build failure in #1245.

Fix experimental extension failure in theorem prover targets

---

model/riscv_insts_base.sail
model/riscv_insts_dext.sail
model/riscv_insts_fext.sail
model/riscv_insts_zaamo.sail
model/riscv_insts_zbb.sail
model/riscv_insts_zbkb.sail
model/riscv_insts_zbs.sail
model/riscv_insts_zfh.sail
model/riscv_insts_zicond.sail

This should help generate bodies for individual instructions from a combined `execute` clause.

Add split attributes to `execute` clauses for the documentation backend.

---

model/riscv_insts_base.sail
model/riscv_insts_svinval.sail
model/riscv_insts_zicbom.sail
model/riscv_smcntrpmf.sail
model/riscv_sscofpmf.sail
model/riscv_sys_control.sail
model/riscv_sys_exceptions.sail
model/riscv_sys_regs.sail
model/riscv_types.sail
model/riscv_vmem_pte.sail
model/riscv_zkr_control.sail

- Add `VirtualUser` and `VirtualSupervisor` to the existing `Privilege` enum
- Rename `privLevel_bits` to `nominalPrivLevel_bits` and add conversions for VS and VU to bits
- Add placeholder to all `match cur_privilege` statements, mark VS and VU branches as unimplemented

Add VU and VS privilege level

---

model/core/callbacks.sail
model/core/types.sail
model/core/types_common.sail
model/core/types_ext.sail
model/postlude/step.sail
model/sys/mem.sail
model/sys/sys_control.sail

Switch `exc_code` to 6 bits, [0, 64). For exceptions, higher values are reserved and can't be implemented without significant changes because there would be no space in `medeleg[h]`.
For interrupts, they are actually even further limited to [0, xlen), unless you have AIA which adds `mieh` and so on.
I also changed the functions to mappings which is a bit nicer and removes the need for `num_of_ExceptionType()`.
It's unfortunate that we have to use binary literals but it's not too bad.

Improve exception code types

---

model/CMakeLists.txt

This is needed to generate hyperlinks in Sail code embedded in Asciidoc.

Add --doc-embed-with-location when building JSON bundle

---

c_emulator/CMakeLists.txt
c_emulator/config_utils.cpp

- Ensure that `config_schema.h` gets regenerated when the schema file changes.
This bug is triggered when switching between git branches that have different schemas.
- Give a more informative error message on config parsing errors.
This now gives (for e.g.):
`Error: Cannot parse configuration in <path>/rv32d_v128_e32.json: Invalid value at line 85 and column 20.`
versus the rather abrupt:
`Error: Invalid value at line 85 and column 20`

A couple of fixes for config schema validation.

---

.github/workflows/ci.yml
doc/ChangeLog.md

Runs the first 20,000,000 instructions of Linux boot as part of CI. This takes ~25 minutes, which is the same length as the existing CI jobs. The current checking is a couple of basic grep strings.

Add linux boot to CI

---

README.md
c_emulator/riscv_sim.cpp
config/config.json.in
doc/ChangeLog.md
model/core/prelude.sail
model/core/range_util.sail
model/extensions/Zicbom/zicbom_insts.sail
model/postlude/device_tree.sail
model/postlude/model.sail
model/postlude/validate_config.sail
model/riscv.sail_project
model/sys/mem.sail
model/sys/platform.sail
model/sys/pma.sail

Add basic support for static PMAs specified in the config file. Support for the AMO level is not fully added yet because it needs to be added to `AccessType`.
This also adds an implication operator `==>` which is useful for writing SMT properties.

Add basic static PMA support

---

.github/workflows/compile-lean.yml

Use the official Lean GitHub action. This simplifies the workflow and fixes the recent installation issue that has come up in CI for Lean.

Use lean-action in Lean CI job
